## Output s and their formats:
nic_class.csv has two columns : 'class' and 'details' both are strings, 'class' is a 4 digit nic code

nic_subclass.csv has two colmns : 'subclass' and 'details', both of them are strings, 'subclass' is a 5 digit nic code

nic_group.csv has two columns: 'group' and 'details', both are strings, 'group' is 3 digit nic code

nic_division.csv  has three columns: 'division', 'details' and 'name', all of them are strings. 'division' is 2 digit nic code. and 'details' is the description of all groups,classes,subclasses under that division. 'name is the 'name' of division 

nic_section.csv has three columns: 'section', 'details' and 'name', all of them are strings. 'section' is 1 alphabet nic code. and 'details' is the description of all divisions,groups,classes,subclasses under that division. 'name' is the name of section.

## Details about the NIC document
All the codes are expressed under the classes 'group','class','subclass,

subclass has code with 5 letters

class has code with 4 letters

group has code with 3 letters

In [1]:
import numpy as np
import pandas as pd

In [2]:
nic_df = pd.read_csv("new_nic.csv",names=['group','class','subclass','details','column5','column6','column7','column8','column9','column10','column11','column12'])

### cleaning #NAME entries
in excel, when a formula with no meaning is given it return #NAME in that cell, so we have to check if we there is any such case like that in this csv and clean it. wait, it's not possible?

In [3]:
# nic_df
sampledf = nic_df.copy()[4630:]
sampledf

group class subclass                                            details  \
4630   NaN   NaN      NaN  subsistence activity, they are classified to t...   
4631   NaN   NaN      NaN                                    industry of NIC   
4632   NaN   NaN      NaN  98100 Undifferentiated goods-producing activit...   
4633   NaN   NaN      NaN                                                use   
4634   NaN   982      NaN  982 undifferentiated service-producing activit...   
4635   NaN   NaN      NaN                                            own use   
4636   NaN   NaN      NaN  9820 undifferentiated service-producing activi...   
4637   NaN   NaN      NaN                                                use   
4638   NaN   NaN      NaN  This class contains the undifferentiated subsi...   
4639   NaN   NaN      NaN  activities of households. These activities inc...   
4640   NaN   NaN      NaN  for household members and other services produ...   
4641   NaN   NaN      NaN  its own subsistence. In application, if househ...   
4642   NaN   NaN      NaN  production of multiple goods for subsistence p...   
4643   NaN   NaN      NaN  the undifferentiated goods-producing subsisten...   
4644   NaN   NaN      NaN  98200 Undifferentiated service-producing activ...   
4645   NaN   NaN      NaN                                                use   
4646   NaN   NaN      NaN  SECTION U: ACTIVITIES OF EXTRATERRITORIAL ORGA...   
4647   NaN   NaN      NaN  DiviSion 99 : aCtivitieS oF extraterritorial o...   
4648   NaN   990      NaN  990 activities of extraterritorial organizatio...   
4649   NaN   NaN      NaN  9900 activities of extraterritorial organizati...   
4650   NaN   NaN      NaN  This class includes the activities of internat...   
4651   NaN   NaN      NaN  United Nations and its agencies, IMF, World Ba...   
4652   NaN   NaN      NaN                                          OPEC etc.   
4653   NaN   NaN      NaN  99000 Activities of extraterritorial organizat...   

     column5 column6 column7 column8 column9 column10 column11 column12  
4630     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4631     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4632     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4633     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4634     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4635     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4636     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4637     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4638     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4639     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4640     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4641     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4642     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4643     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4644     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4645     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4646     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4647     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4648     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4649     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4650     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4651     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4652     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4653     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN

### detaching nic codes which are mixed up with description

some of the rows has no entries under group,class or subclass but all those nic codes are mixed up with details column.
I have manually seperated classes and groups as they are less in number, following code detaches those mix-ups and put them in the right place

In [4]:
def numberpartitioner(k):
    if (type(k[0])==type('a')):
#         print(k)
#         print(k[0],"considered as string \n")
        return k
        pass
    else:
        try :
            k[0]= int(k[1].split(' ',1)[0])
            k[1] = k[1].split(' ',1)[1]
            return k
        except:
            return k
            pass

In [5]:
fakedf = (sampledf[["subclass","details"]][:].T.apply(numberpartitioner)).T
sampledf[["subclass","details"]]=fakedf
sampledf

group class subclass                                            details  \
4630   NaN   NaN      NaN  subsistence activity, they are classified to t...   
4631   NaN   NaN      NaN                                    industry of NIC   
4632   NaN   NaN    98100  Undifferentiated goods-producing activities of...   
4633   NaN   NaN      NaN                                                use   
4634   NaN   982      982  undifferentiated service-producing activities ...   
4635   NaN   NaN      NaN                                            own use   
4636   NaN   NaN     9820  undifferentiated service-producing activities ...   
4637   NaN   NaN      NaN                                                use   
4638   NaN   NaN      NaN  This class contains the undifferentiated subsi...   
4639   NaN   NaN      NaN  activities of households. These activities inc...   
4640   NaN   NaN      NaN  for household members and other services produ...   
4641   NaN   NaN      NaN  its own subsistence. In application, if househ...   
4642   NaN   NaN      NaN  production of multiple goods for subsistence p...   
4643   NaN   NaN      NaN  the undifferentiated goods-producing subsisten...   
4644   NaN   NaN    98200  Undifferentiated service-producing activities ...   
4645   NaN   NaN      NaN                                                use   
4646   NaN   NaN      NaN  SECTION U: ACTIVITIES OF EXTRATERRITORIAL ORGA...   
4647   NaN   NaN      NaN  DiviSion 99 : aCtivitieS oF extraterritorial o...   
4648   NaN   990      990  activities of extraterritorial organizations a...   
4649   NaN   NaN     9900  activities of extraterritorial organizations a...   
4650   NaN   NaN      NaN  This class includes the activities of internat...   
4651   NaN   NaN      NaN  United Nations and its agencies, IMF, World Ba...   
4652   NaN   NaN      NaN                                          OPEC etc.   
4653   NaN   NaN    99000  Activities of extraterritorial organizations a...   

     column5 column6 column7 column8 column9 column10 column11 column12  
4630     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4631     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4632     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4633     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4634     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4635     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4636     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4637     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4638     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4639     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4640     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4641     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4642     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4643     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4644     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4645     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4646     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4647     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4648     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4649     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4650     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4651     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4652     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4653     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN

In [6]:
sampledf

group class subclass                                            details  \
4630   NaN   NaN      NaN  subsistence activity, they are classified to t...   
4631   NaN   NaN      NaN                                    industry of NIC   
4632   NaN   NaN    98100  Undifferentiated goods-producing activities of...   
4633   NaN   NaN      NaN                                                use   
4634   NaN   982      982  undifferentiated service-producing activities ...   
4635   NaN   NaN      NaN                                            own use   
4636   NaN   NaN     9820  undifferentiated service-producing activities ...   
4637   NaN   NaN      NaN                                                use   
4638   NaN   NaN      NaN  This class contains the undifferentiated subsi...   
4639   NaN   NaN      NaN  activities of households. These activities inc...   
4640   NaN   NaN      NaN  for household members and other services produ...   
4641   NaN   NaN      NaN  its own subsistence. In application, if househ...   
4642   NaN   NaN      NaN  production of multiple goods for subsistence p...   
4643   NaN   NaN      NaN  the undifferentiated goods-producing subsisten...   
4644   NaN   NaN    98200  Undifferentiated service-producing activities ...   
4645   NaN   NaN      NaN                                                use   
4646   NaN   NaN      NaN  SECTION U: ACTIVITIES OF EXTRATERRITORIAL ORGA...   
4647   NaN   NaN      NaN  DiviSion 99 : aCtivitieS oF extraterritorial o...   
4648   NaN   990      990  activities of extraterritorial organizations a...   
4649   NaN   NaN     9900  activities of extraterritorial organizations a...   
4650   NaN   NaN      NaN  This class includes the activities of internat...   
4651   NaN   NaN      NaN  United Nations and its agencies, IMF, World Ba...   
4652   NaN   NaN      NaN                                          OPEC etc.   
4653   NaN   NaN    99000  Activities of extraterritorial organizations a...   

     column5 column6 column7 column8 column9 column10 column11 column12  
4630     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4631     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4632     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4633     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4634     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4635     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4636     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4637     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4638     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4639     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4640     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4641     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4642     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4643     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4644     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4645     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4646     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4647     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4648     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4649     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4650     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4651     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4652     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN  
4653     NaN     NaN     NaN     NaN     NaN      NaN      NaN      NaN

In [7]:
fakedf = (nic_df[["subclass","details"]][:].T.apply(numberpartitioner)).T
nic_df[["subclass","details"]]=fakedf
nic_df

group class subclass                                            details  \
0       11   NaN      NaN                     Growing of non-perennial crops   
1      NaN   111      NaN  Growing of cereals (except rice), leguminous c...   
2      NaN   NaN      NaN  This class includes all forms of growing of ce...   
3      NaN   NaN      NaN  oil seeds in open fields, including those cons...   
4      NaN   NaN      NaN  growing of genetically modified crops. The gro...   
5      NaN   NaN      NaN                 combined within agricultural units   
6      NaN   NaN      NaN                               This class excludes:   
7      NaN   NaN      NaN            - growing of maize for fodder, see 0119   
8      NaN   NaN     1111                                   Growing of wheat   
9      NaN   NaN     1112                Growing of jowar, bajra and millets   
10     NaN   NaN     1113                           Growing of other cereals   
11     NaN   NaN     1114  Growing of pulses (dal) and other leguminous c...   
12     NaN   NaN      NaN                               not used as oilseeds   
13     NaN   NaN     1115                        Growing of mustard oil seed   
14     NaN   NaN     1116                      Growing of groundnut oil seed   
15     NaN   NaN     1117                      Growing of sunflower oil seed   
16     NaN   NaN     1118                      Growing of soya bean oil seed   
17     NaN   NaN     1119                         Growing of other oil seeds   
18     NaN   112      NaN                                    Growing of rice   
19     NaN   NaN      NaN  This class includes the growing of rice, inclu...   
20     NaN   NaN      NaN              growing of genetically modified rice.   
21     NaN   NaN     1121                    Organic farming of basmati rice   
22     NaN   NaN     1122                Organic farming of non-basmati rice   
23     NaN   NaN     1123                  Inorganic farming of basmati rice   
24     NaN   NaN     1124              Inorganic farming of non-basmati rice   
25     NaN   113      NaN  Growing of vegetables and melons, roots and tu...   
26     NaN   NaN      NaN                               This class excludes:   
27     NaN   NaN      NaN              - growing of mushroom spawn, see 0130   
28     NaN   NaN      NaN                                             #NAME?   
29     NaN   NaN      NaN                           aromatic crops, see 0128   
...    ...   ...      ...                                                ...   
4624   NaN   NaN      NaN  in a variety of activities that produce goods ...   
4625   NaN   NaN      NaN  These activities include hunting and gathering...   
4626   NaN   NaN      NaN  shelter and clothing and other goods produced ...   
4627   NaN   NaN      NaN  subsistence. In application, if households are...   
4628   NaN   NaN      NaN  of marketed goods, they are classified to the ...   
4629   NaN   NaN      NaN  industry of NIC. If they are principally engag...   
4630   NaN   NaN      NaN  subsistence activity, they are classified to t...   
4631   NaN   NaN      NaN                                    industry of NIC   
4632   NaN   NaN    98100  Undifferentiated goods-producing activities of...   
4633   NaN   NaN      NaN                                                use   
4634   NaN   982      982  undifferentiated service-producing activities ...   
4635   NaN   NaN      NaN                                            own use   
4636   NaN   NaN     9820  undifferentiated service-producing activities ...   
4637   NaN   NaN      NaN                                                use   
4638   NaN   NaN      NaN  This class contains the undifferentiated subsi...   
4639   NaN   NaN      NaN  activities of households. These activities inc...   
4640   NaN   NaN      NaN  for household members and other services produ...   
4641   NaN   NaN      NaN  its own subsistence. In application, if househ...   
4642 

In [8]:
# nic_df.to_csv('nicodesuntangles.csv')

### NIC csv after dropping sections and divisions using openrefine.

In [9]:
nic_df = pd.read_csv("nicodesuntangles-csv.csv")#,names=['group','class','subclass','details','column5','column6','column7','column8','column9','column10','column11','column12'])

there are false entries in subclass with 4 integers or 3 integers in subclass and 3 integers in class

#### subclass 
when group is 11, 1111 -  is correct entry

where as when group is 220 , 220 or 2200 is incorrect.

##### class
when group is 11, 111 is correct entry

where as when group is 220, 220 is false entry.

solution is to exploit that there should not be any codes in class or subclass when there are codes in groups.

and we don't need to care about Nan because we can't compare nans with each other

|||ly no codes in subclass if there is in class.

In [10]:
for row in range(nic_df.shape[0]):
#     if (type(nic_df["subclass"][row])==type('a')) and (type(nic_df["subclass"][row])==type('a'))
    if (nic_df["subclass"][row] == nic_df["class"][row]) or (nic_df["subclass"][row] == nic_df["group"][row]):
        nic_df["subclass"][row] = np.nan
    if (nic_df["class"][row] == nic_df["group"][row]):
        nic_df["class"][row] = np.nan
# nic_df['group'][0]=np.nan

nic_df

#check that earlier on 4597th row, 990 was in both group and subclass, now subclass thing has been turned to NaN

group class subclass                                            details  \
0       11   NaN      NaN                     Growing of non-perennial crops   
1      NaN   111      NaN  Growing of cereals (except rice), leguminous c...   
2      NaN   NaN      NaN  This class includes all forms of growing of ce...   
3      NaN   NaN      NaN  oil seeds in open fields, including those cons...   
4      NaN   NaN      NaN  growing of genetically modified crops. The gro...   
5      NaN   NaN      NaN                 combined within agricultural units   
6      NaN   NaN      NaN                               This class excludes:   
7      NaN   NaN      NaN            - growing of maize for fodder, see 0119   
8      NaN   NaN     1111                                   Growing of wheat   
9      NaN   NaN     1112                Growing of jowar, bajra and millets   
10     NaN   NaN     1113                           Growing of other cereals   
11     NaN   NaN     1114  Growing of pulses (dal) and other leguminous c...   
12     NaN   NaN      NaN                               not used as oilseeds   
13     NaN   NaN     1115                        Growing of mustard oil seed   
14     NaN   NaN     1116                      Growing of groundnut oil seed   
15     NaN   NaN     1117                      Growing of sunflower oil seed   
16     NaN   NaN     1118                      Growing of soya bean oil seed   
17     NaN   NaN     1119                         Growing of other oil seeds   
18     NaN   112      NaN                                    Growing of rice   
19     NaN   NaN      NaN  This class includes the growing of rice, inclu...   
20     NaN   NaN      NaN              growing of genetically modified rice.   
21     NaN   NaN     1121                    Organic farming of basmati rice   
22     NaN   NaN     1122                Organic farming of non-basmati rice   
23     NaN   NaN     1123                  Inorganic farming of basmati rice   
24     NaN   NaN     1124              Inorganic farming of non-basmati rice   
25     NaN   113      NaN  Growing of vegetables and melons, roots and tu...   
26     NaN   NaN      NaN                               This class excludes:   
27     NaN   NaN      NaN              - growing of mushroom spawn, see 0130   
28     NaN   NaN      NaN                                             #NAME?   
29     NaN   NaN      NaN                           aromatic crops, see 0128   
...    ...   ...      ...                                                ...   
4621   NaN   NaN      NaN  This class includes the undifferenciated subsi...   
4622   NaN   NaN      NaN  activities of households, that is the activiti...   
4623   NaN   NaN      NaN  in a variety of activities that produce goods ...   
4624   NaN   NaN      NaN  These activities include hunting and gathering...   
4625   NaN   NaN      NaN  shelter and clothing and other goods produced ...   
4626   NaN   NaN      NaN  subsistence. In application, if households are...   
4627   NaN   NaN      NaN  of marketed goods, they are classified to the ...   
4628   NaN   NaN      NaN  industry of NIC. If they are principally engag...   
4629   NaN   NaN      NaN  subsistence activity, they are classified to t...   
4630   NaN   NaN      NaN                                    industry of NIC   
4631   NaN   NaN    98100  Undifferentiated goods-producing activities of...   
4632   NaN   NaN      NaN                                                use   
4633   982   NaN      NaN  undifferentiated service-producing activities ...   
4634   NaN   NaN      NaN                                            own use   
4635   NaN  9820      NaN  undifferentiated service-producing activities ...   
4636   NaN   NaN      NaN                                                use   
4637   NaN   NaN      NaN  This class contains the undifferentiated subsi...   
4638   NaN   NaN      NaN  activities of households. These activities inc...   
4639 

In [11]:
# print(nic_df.columns)
# nic_df.drop(['Column'],axis=1,inplace=True)

In [12]:
for row in range(nic_df.shape[0]):
    if (type(nic_df["subclass"][row])==type('a')) and (len(nic_df["subclass"][row]))<5:
#         print(row)
        nic_df["subclass"][row]=(nic_df["subclass"][row]).zfill(5)
    if (type(nic_df["class"][row])==type('a')) and (len(nic_df["class"][row]))<4:
        nic_df["class"][row]=(nic_df["class"][row]).zfill(4)
    if (type(nic_df["group"][row])==type('a')) and (len(nic_df["group"][row]))<3:
        nic_df["group"][row]=(nic_df["group"][row]).zfill(3)   


In [13]:
nic_df

group class subclass                                            details  \
0      011   NaN      NaN                     Growing of non-perennial crops   
1      NaN  0111      NaN  Growing of cereals (except rice), leguminous c...   
2      NaN   NaN      NaN  This class includes all forms of growing of ce...   
3      NaN   NaN      NaN  oil seeds in open fields, including those cons...   
4      NaN   NaN      NaN  growing of genetically modified crops. The gro...   
5      NaN   NaN      NaN                 combined within agricultural units   
6      NaN   NaN      NaN                               This class excludes:   
7      NaN   NaN      NaN            - growing of maize for fodder, see 0119   
8      NaN   NaN    01111                                   Growing of wheat   
9      NaN   NaN    01112                Growing of jowar, bajra and millets   
10     NaN   NaN    01113                           Growing of other cereals   
11     NaN   NaN    01114  Growing of pulses (dal) and other leguminous c...   
12     NaN   NaN      NaN                               not used as oilseeds   
13     NaN   NaN    01115                        Growing of mustard oil seed   
14     NaN   NaN    01116                      Growing of groundnut oil seed   
15     NaN   NaN    01117                      Growing of sunflower oil seed   
16     NaN   NaN    01118                      Growing of soya bean oil seed   
17     NaN   NaN    01119                         Growing of other oil seeds   
18     NaN  0112      NaN                                    Growing of rice   
19     NaN   NaN      NaN  This class includes the growing of rice, inclu...   
20     NaN   NaN      NaN              growing of genetically modified rice.   
21     NaN   NaN    01121                    Organic farming of basmati rice   
22     NaN   NaN    01122                Organic farming of non-basmati rice   
23     NaN   NaN    01123                  Inorganic farming of basmati rice   
24     NaN   NaN    01124              Inorganic farming of non-basmati rice   
25     NaN  0113      NaN  Growing of vegetables and melons, roots and tu...   
26     NaN   NaN      NaN                               This class excludes:   
27     NaN   NaN      NaN              - growing of mushroom spawn, see 0130   
28     NaN   NaN      NaN                                             #NAME?   
29     NaN   NaN      NaN                           aromatic crops, see 0128   
...    ...   ...      ...                                                ...   
4621   NaN   NaN      NaN  This class includes the undifferenciated subsi...   
4622   NaN   NaN      NaN  activities of households, that is the activiti...   
4623   NaN   NaN      NaN  in a variety of activities that produce goods ...   
4624   NaN   NaN      NaN  These activities include hunting and gathering...   
4625   NaN   NaN      NaN  shelter and clothing and other goods produced ...   
4626   NaN   NaN      NaN  subsistence. In application, if households are...   
4627   NaN   NaN      NaN  of marketed goods, they are classified to the ...   
4628   NaN   NaN      NaN  industry of NIC. If they are principally engag...   
4629   NaN   NaN      NaN  subsistence activity, they are classified to t...   
4630   NaN   NaN      NaN                                    industry of NIC   
4631   NaN   NaN    98100  Undifferentiated goods-producing activities of...   
4632   NaN   NaN      NaN                                                use   
4633   982   NaN      NaN  undifferentiated service-producing activities ...   
4634   NaN   NaN      NaN                                            own use   
4635   NaN  9820      NaN  undifferentiated service-producing activities ...   
4636   NaN   NaN      NaN                                                use   
4637   NaN   NaN      NaN  This class contains the undifferentiated subsi...   
4638   NaN   NaN      NaN  activities of households. These activities inc...   
4639 

filling subclass nan values with corresponding class/group values, so that we can apply ffill later and apply group by to get nice subclass-description.

similarly for class and group

In [14]:
for row in range(nic_df.shape[0]):
    if (type(nic_df["subclass"][row])!=type('a')) and (type(nic_df["class"][row])==type('a')):
        nic_df["subclass"][row]=nic_df["class"][row]
    if (type(nic_df["subclass"][row])!=type('a')) and (type(nic_df["class"][row])!=type('a')) and (type(nic_df["group"][row])==type('a')):
        nic_df["subclass"][row]=nic_df["group"][row]
# type(nic_df["group"][2])
nic_df

group class subclass                                            details  \
0      011   NaN      011                     Growing of non-perennial crops   
1      NaN  0111     0111  Growing of cereals (except rice), leguminous c...   
2      NaN   NaN      NaN  This class includes all forms of growing of ce...   
3      NaN   NaN      NaN  oil seeds in open fields, including those cons...   
4      NaN   NaN      NaN  growing of genetically modified crops. The gro...   
5      NaN   NaN      NaN                 combined within agricultural units   
6      NaN   NaN      NaN                               This class excludes:   
7      NaN   NaN      NaN            - growing of maize for fodder, see 0119   
8      NaN   NaN    01111                                   Growing of wheat   
9      NaN   NaN    01112                Growing of jowar, bajra and millets   
10     NaN   NaN    01113                           Growing of other cereals   
11     NaN   NaN    01114  Growing of pulses (dal) and other leguminous c...   
12     NaN   NaN      NaN                               not used as oilseeds   
13     NaN   NaN    01115                        Growing of mustard oil seed   
14     NaN   NaN    01116                      Growing of groundnut oil seed   
15     NaN   NaN    01117                      Growing of sunflower oil seed   
16     NaN   NaN    01118                      Growing of soya bean oil seed   
17     NaN   NaN    01119                         Growing of other oil seeds   
18     NaN  0112     0112                                    Growing of rice   
19     NaN   NaN      NaN  This class includes the growing of rice, inclu...   
20     NaN   NaN      NaN              growing of genetically modified rice.   
21     NaN   NaN    01121                    Organic farming of basmati rice   
22     NaN   NaN    01122                Organic farming of non-basmati rice   
23     NaN   NaN    01123                  Inorganic farming of basmati rice   
24     NaN   NaN    01124              Inorganic farming of non-basmati rice   
25     NaN  0113     0113  Growing of vegetables and melons, roots and tu...   
26     NaN   NaN      NaN                               This class excludes:   
27     NaN   NaN      NaN              - growing of mushroom spawn, see 0130   
28     NaN   NaN      NaN                                             #NAME?   
29     NaN   NaN      NaN                           aromatic crops, see 0128   
...    ...   ...      ...                                                ...   
4621   NaN   NaN      NaN  This class includes the undifferenciated subsi...   
4622   NaN   NaN      NaN  activities of households, that is the activiti...   
4623   NaN   NaN      NaN  in a variety of activities that produce goods ...   
4624   NaN   NaN      NaN  These activities include hunting and gathering...   
4625   NaN   NaN      NaN  shelter and clothing and other goods produced ...   
4626   NaN   NaN      NaN  subsistence. In application, if households are...   
4627   NaN   NaN      NaN  of marketed goods, they are classified to the ...   
4628   NaN   NaN      NaN  industry of NIC. If they are principally engag...   
4629   NaN   NaN      NaN  subsistence activity, they are classified to t...   
4630   NaN   NaN      NaN                                    industry of NIC   
4631   NaN   NaN    98100  Undifferentiated goods-producing activities of...   
4632   NaN   NaN      NaN                                                use   
4633   982   NaN      982  undifferentiated service-producing activities ...   
4634   NaN   NaN      NaN                                            own use   
4635   NaN  9820     9820  undifferentiated service-producing activities ...   
4636   NaN   NaN      NaN                                                use   
4637   NaN   NaN      NaN  This class contains the undifferentiated subsi...   
4638   NaN   NaN      NaN  activities of households. These activities inc...   
4639 

In [15]:
nic_df["subclass"]=nic_df["subclass"].ffill()

In [16]:
for row in range(nic_df.shape[0]):
    if (type(nic_df["class"][row])!=type('a')) and (type(nic_df["group"][row])==type('a')):
        nic_df["class"][row]=nic_df["group"][row]
#     if (type(nic_df["subclass"][row])!=type('a')) and (type(nic_df["class"][row])!=type('a')) and (type(nic_df["group"][row])==type('a')):
#         nic_df["subclass"][row]=nic_df["group"][row]
# type(nic_df["group"][2])
nic_df["class"]=nic_df["class"].ffill()
nic_df["group"] = nic_df["group"].ffill()
nic_df

group class subclass                                            details  \
0      011   011      011                     Growing of non-perennial crops   
1      011  0111     0111  Growing of cereals (except rice), leguminous c...   
2      011  0111     0111  This class includes all forms of growing of ce...   
3      011  0111     0111  oil seeds in open fields, including those cons...   
4      011  0111     0111  growing of genetically modified crops. The gro...   
5      011  0111     0111                 combined within agricultural units   
6      011  0111     0111                               This class excludes:   
7      011  0111     0111            - growing of maize for fodder, see 0119   
8      011  0111    01111                                   Growing of wheat   
9      011  0111    01112                Growing of jowar, bajra and millets   
10     011  0111    01113                           Growing of other cereals   
11     011  0111    01114  Growing of pulses (dal) and other leguminous c...   
12     011  0111    01114                               not used as oilseeds   
13     011  0111    01115                        Growing of mustard oil seed   
14     011  0111    01116                      Growing of groundnut oil seed   
15     011  0111    01117                      Growing of sunflower oil seed   
16     011  0111    01118                      Growing of soya bean oil seed   
17     011  0111    01119                         Growing of other oil seeds   
18     011  0112     0112                                    Growing of rice   
19     011  0112     0112  This class includes the growing of rice, inclu...   
20     011  0112     0112              growing of genetically modified rice.   
21     011  0112    01121                    Organic farming of basmati rice   
22     011  0112    01122                Organic farming of non-basmati rice   
23     011  0112    01123                  Inorganic farming of basmati rice   
24     011  0112    01124              Inorganic farming of non-basmati rice   
25     011  0113     0113  Growing of vegetables and melons, roots and tu...   
26     011  0113     0113                               This class excludes:   
27     011  0113     0113              - growing of mushroom spawn, see 0130   
28     011  0113     0113                                             #NAME?   
29     011  0113     0113                           aromatic crops, see 0128   
...    ...   ...      ...                                                ...   
4621   981  9810     9810  This class includes the undifferenciated subsi...   
4622   981  9810     9810  activities of households, that is the activiti...   
4623   981  9810     9810  in a variety of activities that produce goods ...   
4624   981  9810     9810  These activities include hunting and gathering...   
4625   981  9810     9810  shelter and clothing and other goods produced ...   
4626   981  9810     9810  subsistence. In application, if households are...   
4627   981  9810     9810  of marketed goods, they are classified to the ...   
4628   981  9810     9810  industry of NIC. If they are principally engag...   
4629   981  9810     9810  subsistence activity, they are classified to t...   
4630   981  9810     9810                                    industry of NIC   
4631   981  9810    98100  Undifferentiated goods-producing activities of...   
4632   981  9810    98100                                                use   
4633   982   982      982  undifferentiated service-producing activities ...   
4634   982   982      982                                            own use   
4635   982  9820     9820  undifferentiated service-producing activities ...   
4636   982  9820     9820                                                use   
4637   982  9820     9820  This class contains the undifferentiated subsi...   
4638   982  9820     9820  activities of households. These activities inc...   
4639 

some of the information is split into different coulmns, though it's mainly residing in 'details' column, other columns has some info. first replace all nan values with '', so that we can concatenate the strings 

In [17]:
nic_df[['column5','column6','column7','column8','column9','column10','column11','column12']] = nic_df[['column5','column6','column7','column8','column9','column10','column11','column12']].fillna("")
# checking if concatenating between columns works
print(type(nic_df["group"]))
s1=pd.Series(["ha","he",""])
s2=pd.Series(["sho","sha","ki"])
s3=(s1.dropna()+s2.dropna())
print(s3.dropna())
nic_df
# print(type(nic_df["subclass"][100])==type(0.0))
# print(type("errr")==type('a'))
# if 2 and 3 and not(4):
#     print("yay")
# else:
#     print("boo")

<class 'pandas.core.series.Series'>
0    hasho
1    hesha
2       ki
dtype: object


group class subclass                                            details  \
0      011   011      011                     Growing of non-perennial crops   
1      011  0111     0111  Growing of cereals (except rice), leguminous c...   
2      011  0111     0111  This class includes all forms of growing of ce...   
3      011  0111     0111  oil seeds in open fields, including those cons...   
4      011  0111     0111  growing of genetically modified crops. The gro...   
5      011  0111     0111                 combined within agricultural units   
6      011  0111     0111                               This class excludes:   
7      011  0111     0111            - growing of maize for fodder, see 0119   
8      011  0111    01111                                   Growing of wheat   
9      011  0111    01112                Growing of jowar, bajra and millets   
10     011  0111    01113                           Growing of other cereals   
11     011  0111    01114  Growing of pulses (dal) and other leguminous c...   
12     011  0111    01114                               not used as oilseeds   
13     011  0111    01115                        Growing of mustard oil seed   
14     011  0111    01116                      Growing of groundnut oil seed   
15     011  0111    01117                      Growing of sunflower oil seed   
16     011  0111    01118                      Growing of soya bean oil seed   
17     011  0111    01119                         Growing of other oil seeds   
18     011  0112     0112                                    Growing of rice   
19     011  0112     0112  This class includes the growing of rice, inclu...   
20     011  0112     0112              growing of genetically modified rice.   
21     011  0112    01121                    Organic farming of basmati rice   
22     011  0112    01122                Organic farming of non-basmati rice   
23     011  0112    01123                  Inorganic farming of basmati rice   
24     011  0112    01124              Inorganic farming of non-basmati rice   
25     011  0113     0113  Growing of vegetables and melons, roots and tu...   
26     011  0113     0113                               This class excludes:   
27     011  0113     0113              - growing of mushroom spawn, see 0130   
28     011  0113     0113                                             #NAME?   
29     011  0113     0113                           aromatic crops, see 0128   
...    ...   ...      ...                                                ...   
4621   981  9810     9810  This class includes the undifferenciated subsi...   
4622   981  9810     9810  activities of households, that is the activiti...   
4623   981  9810     9810  in a variety of activities that produce goods ...   
4624   981  9810     9810  These activities include hunting and gathering...   
4625   981  9810     9810  shelter and clothing and other goods produced ...   
4626   981  9810     9810  subsistence. In application, if households are...   
4627   981  9810     9810  of marketed goods, they are classified to the ...   
4628   981  9810     9810  industry of NIC. If they are principally engag...   
4629   981  9810     9810  subsistence activity, they are classified to t...   
4630   981  9810     9810                                    industry of NIC   
4631   981  9810    98100  Undifferentiated goods-producing activities of...   
4632   981  9810    98100                                                use   
4633   982   982      982  undifferentiated service-producing activities ...   
4634   982   982      982                                            own use   
4635   982  9820     9820  undifferentiated service-producing activities ...   
4636   982  9820     9820                                                use   
4637   982  9820     9820  This class contains the undifferentiated subsi...   
4638   982  9820     9820  activities of households. These activities inc...   
4639 

In [18]:
nic_df["details"]=nic_df["details"]+nic_df["column5"]+nic_df["column6"]+nic_df["column7"]+nic_df["column8"]+nic_df["column9"]+nic_df["column10"]+nic_df["column11"]+nic_df["column12"]

In [19]:
nic_df.drop(columns = ['column5','column6','column7','column8','column9','column10','column11','column12'],inplace=True)
nic_df

group class subclass                                            details
0      011   011      011                     Growing of non-perennial crops
1      011  0111     0111  Growing of cereals (except rice), leguminous c...
2      011  0111     0111  This class includes all forms of growing of ce...
3      011  0111     0111  oil seeds in open fields, including those cons...
4      011  0111     0111  growing of genetically modified crops. The gro...
5      011  0111     0111                 combined within agricultural units
6      011  0111     0111                               This class excludes:
7      011  0111     0111            - growing of maize for fodder, see 0119
8      011  0111    01111                                   Growing of wheat
9      011  0111    01112                Growing of jowar, bajra and millets
10     011  0111    01113                           Growing of other cereals
11     011  0111    01114  Growing of pulses (dal) and other leguminous c...
12     011  0111    01114                               not used as oilseeds
13     011  0111    01115                        Growing of mustard oil seed
14     011  0111    01116                      Growing of groundnut oil seed
15     011  0111    01117                      Growing of sunflower oil seed
16     011  0111    01118                      Growing of soya bean oil seed
17     011  0111    01119                         Growing of other oil seeds
18     011  0112     0112                                    Growing of rice
19     011  0112     0112  This class includes the growing of rice, inclu...
20     011  0112     0112              growing of genetically modified rice.
21     011  0112    01121                    Organic farming of basmati rice
22     011  0112    01122                Organic farming of non-basmati rice
23     011  0112    01123                  Inorganic farming of basmati rice
24     011  0112    01124              Inorganic farming of non-basmati rice
25     011  0113     0113  Growing of vegetables and melons, roots and tu...
26     011  0113     0113                               This class excludes:
27     011  0113     0113              - growing of mushroom spawn, see 0130
28     011  0113     0113                                             #NAME?
29     011  0113     0113                           aromatic crops, see 0128
...    ...   ...      ...                                                ...
4621   981  9810     9810  This class includes the undifferenciated subsi...
4622   981  9810     9810  activities of households, that is the activiti...
4623   981  9810     9810  in a variety of activities that produce goods ...
4624   981  9810     9810  These activities include hunting and gathering...
4625   981  9810     9810  shelter and clothing and other goods produced ...
4626   981  9810     9810  subsistence. In application, if households are...
4627   981  9810     9810  of marketed goods, they are classified to the ...
4628   981  9810     9810  industry of NIC. If they are principally engag...
4629   981  9810     9810  subsistence activity, they are classified to t...
4630   981  9810     9810                                    industry of NIC
4631   981  9810    98100  Undifferentiated goods-producing activities of...
4632   981  9810    98100                                                use
4633   982   982      982  undifferentiated service-producing activities ...
4634   982   982      982                                            own use
4635   982  9820     9820  undifferentiated service-producing activities ...
4636   982  9820     9820                                                use
4637   982  9820     9820  This class contains the undifferentiated subsi...
4638   982  9820     9820  activities of households. These activities inc...
4639   982  9820     9820  for household members and other services produ...
4640   982  9820     9820  its own subsistence. In application, if househ...
4

In [20]:
nic_df_group = nic_df.copy()
nic_df_class = nic_df.copy()
nic_df_subclass = nic_df.copy()

In [21]:
# nic_df = nic_df.groupby('subclass').agg(lambda x:list(x))

In [22]:
# nic_df.to_csv('temp.csv')

In [23]:
# nic_df = pd.read_csv('niccode_groupbysubclass.csv')
# nic_df

In [24]:
# nic_df.to_csv('temp1.csv')

by inspection, columns at the starting are created because of parsing the first numerical combination of the detials, which may have occured because they were mentioning some numbers or othe nic category, a very little information is lost here, but it should not be harmful because they are small in number and most of them are descriptions of a group rather than a class or subclass

### creating a df only with subclass codes

In [25]:
for row in range(nic_df_class.shape[0]):
    if len(nic_df_class['class'][row])==4:
        pass
    else:
        nic_df_class.drop(row, inplace=True)
nic_df_class

group class subclass                                            details
1      011  0111     0111  Growing of cereals (except rice), leguminous c...
2      011  0111     0111  This class includes all forms of growing of ce...
3      011  0111     0111  oil seeds in open fields, including those cons...
4      011  0111     0111  growing of genetically modified crops. The gro...
5      011  0111     0111                 combined within agricultural units
6      011  0111     0111                               This class excludes:
7      011  0111     0111            - growing of maize for fodder, see 0119
8      011  0111    01111                                   Growing of wheat
9      011  0111    01112                Growing of jowar, bajra and millets
10     011  0111    01113                           Growing of other cereals
11     011  0111    01114  Growing of pulses (dal) and other leguminous c...
12     011  0111    01114                               not used as oilseeds
13     011  0111    01115                        Growing of mustard oil seed
14     011  0111    01116                      Growing of groundnut oil seed
15     011  0111    01117                      Growing of sunflower oil seed
16     011  0111    01118                      Growing of soya bean oil seed
17     011  0111    01119                         Growing of other oil seeds
18     011  0112     0112                                    Growing of rice
19     011  0112     0112  This class includes the growing of rice, inclu...
20     011  0112     0112              growing of genetically modified rice.
21     011  0112    01121                    Organic farming of basmati rice
22     011  0112    01122                Organic farming of non-basmati rice
23     011  0112    01123                  Inorganic farming of basmati rice
24     011  0112    01124              Inorganic farming of non-basmati rice
25     011  0113     0113  Growing of vegetables and melons, roots and tu...
26     011  0113     0113                               This class excludes:
27     011  0113     0113              - growing of mushroom spawn, see 0130
28     011  0113     0113                                             #NAME?
29     011  0113     0113                           aromatic crops, see 0128
30     011  0113    01131  Growing of asparagus, cabbages, cauliflower, b...
...    ...   ...      ...                                                ...
4616   970  9700    97000                  oF private houSeholDS For oWn uSe
4619   981  9810     9810  undifferentiated goods-producing activities of...
4620   981  9810     9810                                                use
4621   981  9810     9810  This class includes the undifferenciated subsi...
4622   981  9810     9810  activities of households, that is the activiti...
4623   981  9810     9810  in a variety of activities that produce goods ...
4624   981  9810     9810  These activities include hunting and gathering...
4625   981  9810     9810  shelter and clothing and other goods produced ...
4626   981  9810     9810  subsistence. In application, if households are...
4627   981  9810     9810  of marketed goods, they are classified to the ...
4628   981  9810     9810  industry of NIC. If they are principally engag...
4629   981  9810     9810  subsistence activity, they are classified to t...
4630   981  9810     9810                                    industry of NIC
4631   981  9810    98100  Undifferentiated goods-producing activities of...
4632   981  9810    98100                                                use
4635   982  9820     9820  undifferentiated service-producing activities ...
4636   982  9820     9820                                                use
4637   982  9820     9820  This class contains the undifferentiated subsi...
4638   982  9820     9820  activities of households. These activities inc...
4639   982  9820     9820  for household members and other services produ...
4

In [26]:
nic_df_class = nic_df_class.groupby('class').agg(lambda x:list(x))
nic_df_class.drop(columns = ['group','subclass'],inplace=True)
nic_df_class

details
class                                                   
0111   [Growing of cereals (except rice), leguminous ...
0112   [Growing of rice, This class includes the grow...
0113   [Growing of vegetables and melons, roots and t...
0114   [Growing of sugar cane, This class excludes:, ...
0115   [Growing of tobacco, This class includes growi...
0116   [Growing of fibre crops, Growing of cotton, Gr...
0119   [Growing of other non-perennial crop, This cla...
0121   [Growing of grapes, This class includes growin...
0122   [Growing of tropical and subtropical fruits, G...
0123   [Growing of citrus fruits, Growing of oranges,...
0124   [Growing of pome fruits and stone fruits, Grow...
0125   [Growing of other tree and bush fruits and nut...
0126   [Growing of oleaginous fruits, This class excl...
0127   [Growing of beverage crops, Growing of tea, Gr...
0128   [Growing of spices, aromatic, drug and pharmac...
0129   [Growing of other perennial crops, This class ...
0130   [plant propagation, This class includes the pr...
0141   [raising of cattle and buffaloes, This class e...
0142   [raising of horses and other equines, This cla...
0143   [raising and breeding of camels and camelids, ...
0144   [raising of sheep and goats, This class exclud...
0145   [raising of swine/pigs, Raising of swine/pigs ...
0146   [raising of poultry, This class excludes:, - p...
0149   [raising of other animals, This class excludes...
0150   [mixed farming, This class includes the combin...
0161   [Support activities for crop production, This ...
0162   [Support activities for animal production, Thi...
0163   [post-harvest crop activities, This class excl...
0164   [Seed processing for propagation, This class i...
0170   [hunting, trapping and related service activit...
...                                                  ...
9000   [Dramatic arts, music and other arts activitie...
9101   [library and archives activities, This class i...
9102   [museums activities and operation of historica...
9103   [botanical and zoological gardens and nature r...
9200   [Gambling and betting activities, This class i...
9311   [operation of sports facilities, This class in...
9312   [activities of sports clubs, This class includ...
9319   [other sports activities, This class includes ...
9321   [activities of amusement parks and theme parks...
9329   [other amusement and recreation activities n.e...
9411   [activities of business and employers membersh...
9412   [activities of professional membership organiz...
9420   [activities of trade unions, This class includ...
9491   [activities of religious organizations, This c...
9499   [activities of other membership organizations ...
9511   [repair of computers and peripheral equipment,...
9512   [repair of communication equipment, This class...
9521   [repair of consumer electronics, This class in...
9522   [repair of household appliances and home and g...
9523   [repair of footwear and leather goods, Repair ...
9524   [repair of furniture and home furnishings, Rep...
9529   [repair of personal and household goods, n.e.c...
9601   [Washing and (dry-) cleaning of textile and fu...
9602   [hairdressing and other beauty treatment, This...
9603   [Funeral and related activities, This class in...
9609   [other personal service activities n.e.c., Soc...
9700   [activities of households as employers of dome...
9810   [undifferentiated goods-producing activities o...
9820   [undifferentiated service-producing activities...
9900   [activities of extraterritorial organizations ...

[415 rows x 1 columns]

In [27]:
nic_df_class.reset_index(inplace=True)
# nic_df_class.drop('index',axis=1,inplace=True)
nic_df_class

class                                            details
0    0111  [Growing of cereals (except rice), leguminous ...
1    0112  [Growing of rice, This class includes the grow...
2    0113  [Growing of vegetables and melons, roots and t...
3    0114  [Growing of sugar cane, This class excludes:, ...
4    0115  [Growing of tobacco, This class includes growi...
5    0116  [Growing of fibre crops, Growing of cotton, Gr...
6    0119  [Growing of other non-perennial crop, This cla...
7    0121  [Growing of grapes, This class includes growin...
8    0122  [Growing of tropical and subtropical fruits, G...
9    0123  [Growing of citrus fruits, Growing of oranges,...
10   0124  [Growing of pome fruits and stone fruits, Grow...
11   0125  [Growing of other tree and bush fruits and nut...
12   0126  [Growing of oleaginous fruits, This class excl...
13   0127  [Growing of beverage crops, Growing of tea, Gr...
14   0128  [Growing of spices, aromatic, drug and pharmac...
15   0129  [Growing of other perennial crops, This class ...
16   0130  [plant propagation, This class includes the pr...
17   0141  [raising of cattle and buffaloes, This class e...
18   0142  [raising of horses and other equines, This cla...
19   0143  [raising and breeding of camels and camelids, ...
20   0144  [raising of sheep and goats, This class exclud...
21   0145  [raising of swine/pigs, Raising of swine/pigs ...
22   0146  [raising of poultry, This class excludes:, - p...
23   0149  [raising of other animals, This class excludes...
24   0150  [mixed farming, This class includes the combin...
25   0161  [Support activities for crop production, This ...
26   0162  [Support activities for animal production, Thi...
27   0163  [post-harvest crop activities, This class excl...
28   0164  [Seed processing for propagation, This class i...
29   0170  [hunting, trapping and related service activit...
..    ...                                                ...
385  9000  [Dramatic arts, music and other arts activitie...
386  9101  [library and archives activities, This class i...
387  9102  [museums activities and operation of historica...
388  9103  [botanical and zoological gardens and nature r...
389  9200  [Gambling and betting activities, This class i...
390  9311  [operation of sports facilities, This class in...
391  9312  [activities of sports clubs, This class includ...
392  9319  [other sports activities, This class includes ...
393  9321  [activities of amusement parks and theme parks...
394  9329  [other amusement and recreation activities n.e...
395  9411  [activities of business and employers membersh...
396  9412  [activities of professional membership organiz...
397  9420  [activities of trade unions, This class includ...
398  9491  [activities of religious organizations, This c...
399  9499  [activities of other membership organizations ...
400  9511  [repair of computers and peripheral equipment,...
401  9512  [repair of communication equipment, This class...
402  9521  [repair of consumer electronics, This class in...
403  9522  [repair of household appliances and home and g...
404  9523  [repair of footwear and leather goods, Repair ...
405  9524  [repair of furniture and home furnishings, Rep...
406  9529  [repair of personal and household goods, n.e.c...
407  9601  [Washing and (dry-) cleaning of textile and fu...
408  9602  [hairdressing and other beauty treatment, This...
409  9603  [Funeral and related activities, This class in...
410  9609  [other personal service activities n.e.c., Soc...
411  9700  [activities of households as employers of dome...
412  9810  [undifferentiated goods-producing activities o...
413  9820  [undifferentiated service-producing activities...
414  9900  [activities of extraterritorial organizations ...

[415 rows x 2 columns]

so nic_df_class is dataframe with strings of code under class and array of descriptions under details
in NIC, there are 403 subclasses, where as we got 415, having extra wouldn't harm us as we will just be using the ones which are mapped to. so the extra ones just take up a little space

### creating a df only with subclasses

In [28]:
for row in range(nic_df_subclass.shape[0]):
    if len(nic_df_subclass['subclass'][row])==5:
        pass
    else:
        nic_df_subclass.drop(row, inplace=True)
nic_df_subclass
nic_df_subclass = nic_df_subclass.groupby('subclass').agg(lambda x:list(x))
nic_df_subclass.drop(columns = ['group','class'],inplace=True)

In [29]:
nic_df_subclass.reset_index(inplace=True)
nic_df_subclass.drop(index = list(np.arange(9)), inplace=True)
nic_df_subclass
#first 8 entries are rubbish, so drop them

subclass                                            details
9       01111                                 [Growing of wheat]
10      01112              [Growing of jowar, bajra and millets]
11      01113                         [Growing of other cereals]
12      01114  [Growing of pulses (dal) and other leguminous ...
13      01115                      [Growing of mustard oil seed]
14      01116                    [Growing of groundnut oil seed]
15      01117                    [Growing of sunflower oil seed]
16      01118                    [Growing of soya bean oil seed]
17      01119                       [Growing of other oil seeds]
18      01121                  [Organic farming of basmati rice]
19      01122              [Organic farming of non-basmati rice]
20      01123                [Inorganic farming of basmati rice]
21      01124            [Inorganic farming of non-basmati rice]
22      01131  [Growing of asparagus, cabbages, cauliflower, ...
23      01132  [Growing of cucumbers, gherkins, aubergines, t...
24      01133                                 [Growing of onion]
25      01134  [Growing of carrots, beets,turnips, garlic, le...
26      01135  [Growing of potatoes and other tubers such as ...
27      01136                [Growing of mushrooms and truffles]
28      01137    [Growing of vegetable seeds (except beet seed)]
29      01139                    [Growing of vegetables, n.e.c.]
30      01140                            [Growing of sugar cane]
31      01150                               [Growing of tobacco]
32      01161                                [Growing of cotton]
33      01162                                  [Growing of jute]
34      01169                     [Growing of other fibre crops]
35      01191                                  [Growing of rose]
36      01192                             [Growing of gladiolus]
37      01193  [Growing of other flowers, including productio...
38      01199  [Growing of other non-perennial crops includin...
...       ...                                                ...
1316    95111  [Repair and maintenance of computer and periph...
1317    95112  [Repair and maintenance of automated terminals...
1318    95120                [Repair of communication equipment]
1319    95210                   [Repair of consumer electronics]
1320    95221  [Repair and servicing of household appliances ...
1321    95222  [Repair and servicing of home and garden equip...
1322    95230             [Repair of footwear and leather goods]
1323    95240         [Repair of furniture and home furnishings]
1324    95291                               [Repair of bicycles]
1325    95292                [Repair and alteration of clothing]
1326    95293               [Repair and alteration of jewellery]
1327    95294        [Repair of watches, clocks and their parts]
1328    95295                    [Repair of musical instruments]
1329    95299  [Repair of other personal and household goods ...
1330    95494          [Motor driving school (non-professional)]
1331    96010  [Washing and (dry-) cleaning of textile and fu...
1332    96020          [Hairdressing and other beauty treatment]
1333    96030                   [Funeral and related activities]
1334    96091  [Social activities such as escort services, ma...
1335    96092  [Pet care services such as boarding, grooming ...
1336    96903    [Shoe shiners, porters, valet car parkers etc.]
1337    96904  [Coin-operated personal service machines such ...
1338    96905  [Activities of sauna and steam baths, massage ...
1339    96906     [Astrological and spiritualistsâ€™ activities]
1340    96907  [Activities of aaya, dhai, governess, baby sit...
1341    96908  [General household maintenance activities like...
1342    97000  [Activities of households as employers of dome...
1343    98100  [Undifferentiated goods-producing activities o...
1344    98200  [Undifferentiated service-producing activities...
1345    99000  [Activities of extraterri

In [30]:
nic_df_subclass.reset_index(inplace=True)
nic_df_subclass.drop('index',axis=1,inplace=True)
nic_df_subclass

subclass                                            details
0       01111                                 [Growing of wheat]
1       01112              [Growing of jowar, bajra and millets]
2       01113                         [Growing of other cereals]
3       01114  [Growing of pulses (dal) and other leguminous ...
4       01115                      [Growing of mustard oil seed]
5       01116                    [Growing of groundnut oil seed]
6       01117                    [Growing of sunflower oil seed]
7       01118                    [Growing of soya bean oil seed]
8       01119                       [Growing of other oil seeds]
9       01121                  [Organic farming of basmati rice]
10      01122              [Organic farming of non-basmati rice]
11      01123                [Inorganic farming of basmati rice]
12      01124            [Inorganic farming of non-basmati rice]
13      01131  [Growing of asparagus, cabbages, cauliflower, ...
14      01132  [Growing of cucumbers, gherkins, aubergines, t...
15      01133                                 [Growing of onion]
16      01134  [Growing of carrots, beets,turnips, garlic, le...
17      01135  [Growing of potatoes and other tubers such as ...
18      01136                [Growing of mushrooms and truffles]
19      01137    [Growing of vegetable seeds (except beet seed)]
20      01139                    [Growing of vegetables, n.e.c.]
21      01140                            [Growing of sugar cane]
22      01150                               [Growing of tobacco]
23      01161                                [Growing of cotton]
24      01162                                  [Growing of jute]
25      01169                     [Growing of other fibre crops]
26      01191                                  [Growing of rose]
27      01192                             [Growing of gladiolus]
28      01193  [Growing of other flowers, including productio...
29      01199  [Growing of other non-perennial crops includin...
...       ...                                                ...
1307    95111  [Repair and maintenance of computer and periph...
1308    95112  [Repair and maintenance of automated terminals...
1309    95120                [Repair of communication equipment]
1310    95210                   [Repair of consumer electronics]
1311    95221  [Repair and servicing of household appliances ...
1312    95222  [Repair and servicing of home and garden equip...
1313    95230             [Repair of footwear and leather goods]
1314    95240         [Repair of furniture and home furnishings]
1315    95291                               [Repair of bicycles]
1316    95292                [Repair and alteration of clothing]
1317    95293               [Repair and alteration of jewellery]
1318    95294        [Repair of watches, clocks and their parts]
1319    95295                    [Repair of musical instruments]
1320    95299  [Repair of other personal and household goods ...
1321    95494          [Motor driving school (non-professional)]
1322    96010  [Washing and (dry-) cleaning of textile and fu...
1323    96020          [Hairdressing and other beauty treatment]
1324    96030                   [Funeral and related activities]
1325    96091  [Social activities such as escort services, ma...
1326    96092  [Pet care services such as boarding, grooming ...
1327    96903    [Shoe shiners, porters, valet car parkers etc.]
1328    96904  [Coin-operated personal service machines such ...
1329    96905  [Activities of sauna and steam baths, massage ...
1330    96906     [Astrological and spiritualistsâ€™ activities]
1331    96907  [Activities of aaya, dhai, governess, baby sit...
1332    96908  [General household maintenance activities like...
1333    97000  [Activities of households as employers of dome...
1334    98100  [Undifferentiated goods-producing activities o...
1335    98200  [Undifferentiated service-producing activities...
1336    99000  [Activities of extraterri

In [31]:
len(nic_df_subclass['subclass'].unique())

1337

so, nic_df_subclass is a df with nic codes as strings under subclass where as there are array of description under details.
in NIC, there are 1304 subclasses, where as we got 1339, having extra wouldn't harm us as we will just be using the ones which are mapped to. so the extra ones just take up a little space

### creating a df only with groups

In [32]:
nic_df_group = nic_df_group.groupby('group').agg(lambda x:list(x))

In [33]:
nic_df_group.reset_index(inplace=True)
nic_df_group

group  \
0                                                  011   
1                                                  012   
2                                                  013   
3                                                  014   
4                                                  015   
5                                                  016   
6                                                  017   
7                                                  021   
8                                                  022   
9                                                  023   
10                                                 024   
11                                                 031   
12                                                 032   
13                                                 051   
14                                                 052   
15                                                 061   
16                                                 062   
17                                                 071   
18                                                 072   
19                                                 081   
20                                                 089   
21                                                 091   
22                                                 099   
23                                                 101   
24                                                 102   
25                                                 103   
26                                                 104   
27                                                 105   
28                                                 106   
29                                                 107   
..                                                 ...   
218                                                872   
219                                                873   
220                                                879   
221                                                881   
222                                                889   
223                                                900   
224                                                910   
225                                                920   
226                                                931   
227                                                932   
228                                                941   
229                                                942   
230                                                949   
231                                                951   
232                                                952   
233                                                960   
234                                                970   
235                                                981   
236                                                982   
237                                                990   
238                 DiviSion 16 : manuFaCture oF WooDa   
239  DiviSion 18 : printinG anD reproDuCtion oF reC...   
240  DiviSion 23 : manuFaCture oF other non-metalli...   
241  DiviSion 52 : WarehouSinG anD Support aCtiviti...   
242  DiviSion 62 : Computer proGramminG, ConSultanC...   
243                                     DiviSion 70 :a   
244  DiviSion 91 : librarieS, arChiveS, muSeumS anD...   
245  DiviSion 95 : repair oF ComputerS anD perSonal...   
246  Furniture; manuFaCture oF artiCleS oF StraW an...   
247  exCluDeS publiShinG aCtivitieS, See SeCtion J ...   

                                                 class  \
0    [011, 0111, 0111, 0111, 0111, 0111, 0111, 0111...   
1    [012, 0121, 0121, 0121, 0121, 0121, 0122, 0122...   
2    [013, 0130, 0130, 0130, 0130, 0130, 0130, 0130...   
3    [014, 0141, 0141, 0141, 0141, 0141, 0141, 0142...   
4    [015, 0150, 0150, 0150, 0150, 0150, 0150, 0150...   
5    [016, 0161, 0161, 0161, 0161, 0161, 0161, 0161...   
6    [017, 0170, 0170, 0170, 0170, 0170, 0170,

In [34]:
#last 10 rows are garbage, drop them
nic_df_group.drop(index = list(np.arange(238,248)),inplace=True)


In [35]:
nic_df_group.drop(columns = ['class','subclass'],inplace=True)
nic_df_group

group                                            details
0     011  [Growing of non-perennial crops, Growing of ce...
1     012  [Growing of perennial crops, Growing of grapes...
2     013  [plant propagation, plant propagation, This cl...
3     014  [animal production, raising of cattle and buff...
4     015  [mixed farming, mixed farming, This class incl...
5     016  [Support activities to agriculture and post-ha...
6     017  [hunting, trapping and related service activit...
7     021  [Silviculture and other forestry activities, S...
8     022  [logging, logging, This class excludes:, - gro...
9     023  [Gathering of non-wood forest products, Gather...
10    024  [Support services to forestry, Support service...
11    031  [Fishing, Marine fishing, This class excludes:...
12    032  [aquaculture, marine aquaculture, This class e...
13    051  [mining of hard coal, mining of hard coal, Thi...
14    052  [mining of lignite, mining of lignite, This cl...
15    061  [extraction of crude petroleum, extraction of ...
16    062  [extraction of natural gas, extraction of natu...
17    071  [mining of iron ores, mining of iron ores, Thi...
18    072  [mining of non-ferrous metal ores, mining of u...
19    081  [quarrying of stone, sand and clay, quarrying ...
20    089  [mining and quarrying n.e.c., mining of chemic...
21    091  [Support activities for petroleum and natural ...
22    099  [Support activities for other mining and quarr...
23    101  [Processing and preserving of meat, processing...
24    102  [Processing and preserving of fish, crustacean...
25    103  [processing and preserving of fruit and vegeta...
26    104  [manufacture of vegetable and animal oils and ...
27    105  [manufacture of dairy products, manufacture of...
28    106  [manufacture of grain mill products, starches ...
29    107  [manufacture of other food products, manufactu...
..    ...                                                ...
208   843  [Compulsory social security activities, Compul...
209   851  [primary education, primary education, Pre-pri...
210   852  [Secondary education, General secondary educat...
211   853  [higher education, higher education, Higher ed...
212   854  [other education, Sports and recreation educat...
213   855  [educational support services, educational sup...
214   861  [hospital activities, hospital activities, Thi...
215   862  [medical and dental practice activities, medic...
216   869  [other human health activities, other human he...
217   871  [nursing care facilities, nursing care facilit...
218   872  [residential care activities for mental retard...
219   873  [residential care activities for the elderly a...
220   879  [other residential care activities n.e.c., oth...
221   881  [Social work activities without accommodation ...
222   889  [other social work activities without accommod...
223   900  [Creative, arts and entertainment activities, ...
224   910  [libraries, archives, museums and other cultur...
225   920  [Gambling and betting activities, Gambling and...
226   931  [Sports activities, operation of sports facili...
227   932  [other amusement and recreation activities, ac...
228   941  [activities of business, employers and profess...
229   942  [activities of trade unions, activities of tra...
230   949  [activities of other membership organizations,...
231   951  [repair of computers and communication equipme...
232   952  [repair of personal and household goods, repai...
233   960  [other personal service activities, Washing an...
234   970  [activities of households as employers of dome...
235   981  [undifferentiated goods-producing activities o...
236   982  [undifferentiated service-producing activities...
237   990  [activities of extraterritorial organizations ...

[238 rows x 2 columns]

In [36]:
def dearray(array):
    string = ''
    for i in range(len(array)):
        string = string+' ' + str(array[i])
    return string
#     return ' '.join(list(array))

In [37]:
nic_df_group['details'] = nic_df_group['details'].apply(dearray)
nic_df_group

group                                            details
0     011   Growing of non-perennial crops Growing of cer...
1     012   Growing of perennial crops Growing of grapes ...
2     013   plant propagation plant propagation This clas...
3     014   animal production raising of cattle and buffa...
4     015   mixed farming mixed farming This class includ...
5     016   Support activities to agriculture and post-ha...
6     017   hunting, trapping and related service activit...
7     021   Silviculture and other forestry activities Si...
8     022   logging logging This class excludes: - growin...
9     023   Gathering of non-wood forest products Gatheri...
10    024   Support services to forestry Support services...
11    031   Fishing Marine fishing This class excludes: #...
12    032   aquaculture marine aquaculture This class exc...
13    051   mining of hard coal mining of hard coal This ...
14    052   mining of lignite mining of lignite This clas...
15    061   extraction of crude petroleum extraction of c...
16    062   extraction of natural gas extraction of natur...
17    071   mining of iron ores mining of iron ores This ...
18    072   mining of non-ferrous metal ores mining of ur...
19    081   quarrying of stone, sand and clay quarrying o...
20    089   mining and quarrying n.e.c. mining of chemica...
21    091   Support activities for petroleum and natural ...
22    099   Support activities for other mining and quarr...
23    101   Processing and preserving of meat processing ...
24    102   Processing and preserving of fish, crustacean...
25    103   processing and preserving of fruit and vegeta...
26    104   manufacture of vegetable and animal oils and ...
27    105   manufacture of dairy products manufacture of ...
28    106   manufacture of grain mill products, starches ...
29    107   manufacture of other food products manufactur...
..    ...                                                ...
208   843   Compulsory social security activities Compuls...
209   851   primary education primary education Pre-prima...
210   852   Secondary education General secondary educati...
211   853   higher education higher education Higher educ...
212   854   other education Sports and recreation educati...
213   855   educational support services educational supp...
214   861   hospital activities hospital activities This ...
215   862   medical and dental practice activities medica...
216   869   other human health activities other human hea...
217   871   nursing care facilities nursing care faciliti...
218   872   residential care activities for mental retard...
219   873   residential care activities for the elderly a...
220   879   other residential care activities n.e.c. othe...
221   881   Social work activities without accommodation ...
222   889   other social work activities without accommod...
223   900   Creative, arts and entertainment activities D...
224   910   libraries, archives, museums and other cultur...
225   920   Gambling and betting activities Gambling and ...
226   931   Sports activities operation of sports facilit...
227   932   other amusement and recreation activities act...
228   941   activities of business, employers and profess...
229   942   activities of trade unions activities of trad...
230   949   activities of other membership organizations ...
231   951   repair of computers and communication equipme...
232   952   repair of personal and household goods repair...
233   960   other personal service activities Washing and...
234   970   activities of households as employers of dome...
235   981   undifferentiated goods-producing activities o...
236   982   undifferentiated service-producing activities...
237   990   activities of extraterritorial organizations ...

[238 rows x 2 columns]

In [38]:
nic_df_subclass['details'] = nic_df_subclass['details'].apply(dearray)
nic_df_subclass

subclass                                            details
0       01111                                   Growing of wheat
1       01112                Growing of jowar, bajra and millets
2       01113                           Growing of other cereals
3       01114   Growing of pulses (dal) and other leguminous ...
4       01115                        Growing of mustard oil seed
5       01116                      Growing of groundnut oil seed
6       01117                      Growing of sunflower oil seed
7       01118                      Growing of soya bean oil seed
8       01119                         Growing of other oil seeds
9       01121                    Organic farming of basmati rice
10      01122                Organic farming of non-basmati rice
11      01123                  Inorganic farming of basmati rice
12      01124              Inorganic farming of non-basmati rice
13      01131   Growing of asparagus, cabbages, cauliflower, ...
14      01132   Growing of cucumbers, gherkins, aubergines, t...
15      01133                                   Growing of onion
16      01134   Growing of carrots, beets,turnips, garlic, le...
17      01135   Growing of potatoes and other tubers such as ...
18      01136                  Growing of mushrooms and truffles
19      01137      Growing of vegetable seeds (except beet seed)
20      01139                      Growing of vegetables, n.e.c.
21      01140                              Growing of sugar cane
22      01150                                 Growing of tobacco
23      01161                                  Growing of cotton
24      01162                                    Growing of jute
25      01169                       Growing of other fibre crops
26      01191                                    Growing of rose
27      01192                               Growing of gladiolus
28      01193   Growing of other flowers, including productio...
29      01199   Growing of other non-perennial crops includin...
...       ...                                                ...
1307    95111   Repair and maintenance of computer and periph...
1308    95112   Repair and maintenance of automated terminals...
1309    95120                  Repair of communication equipment
1310    95210                     Repair of consumer electronics
1311    95221   Repair and servicing of household appliances ...
1312    95222   Repair and servicing of home and garden equip...
1313    95230               Repair of footwear and leather goods
1314    95240           Repair of furniture and home furnishings
1315    95291                                 Repair of bicycles
1316    95292                  Repair and alteration of clothing
1317    95293                 Repair and alteration of jewellery
1318    95294          Repair of watches, clocks and their parts
1319    95295                      Repair of musical instruments
1320    95299   Repair of other personal and household goods ...
1321    95494            Motor driving school (non-professional)
1322    96010   Washing and (dry-) cleaning of textile and fu...
1323    96020            Hairdressing and other beauty treatment
1324    96030                     Funeral and related activities
1325    96091   Social activities such as escort services, ma...
1326    96092   Pet care services such as boarding, grooming ...
1327    96903      Shoe shiners, porters, valet car parkers etc.
1328    96904   Coin-operated personal service machines such ...
1329    96905   Activities of sauna and steam baths, massage ...
1330    96906       Astrological and spiritualistsâ€™ activities
1331    96907   Activities of aaya, dhai, governess, baby sit...
1332    96908   General household maintenance activities like...
1333    97000   Activities of households as employers of dome...
1334    98100   Undifferentiated goods-producing activities o...
1335    98200   Undifferentiated service-producing activities...
1336    99000   Activities of extraterri

In [39]:
nic_df_class['details'] = nic_df_class['details'].apply(dearray)
nic_df_class

class                                            details
0    0111   Growing of cereals (except rice), leguminous ...
1    0112   Growing of rice This class includes the growi...
2    0113   Growing of vegetables and melons, roots and t...
3    0114   Growing of sugar cane This class excludes: - ...
4    0115   Growing of tobacco This class includes growin...
5    0116   Growing of fibre crops Growing of cotton Grow...
6    0119   Growing of other non-perennial crop This clas...
7    0121   Growing of grapes This class includes growing...
8    0122   Growing of tropical and subtropical fruits Gr...
9    0123   Growing of citrus fruits Growing of oranges G...
10   0124   Growing of pome fruits and stone fruits Growi...
11   0125   Growing of other tree and bush fruits and nut...
12   0126   Growing of oleaginous fruits This class exclu...
13   0127   Growing of beverage crops Growing of tea Grow...
14   0128   Growing of spices, aromatic, drug and pharmac...
15   0129   Growing of other perennial crops This class e...
16   0130   plant propagation This class includes the pro...
17   0141   raising of cattle and buffaloes This class ex...
18   0142   raising of horses and other equines This clas...
19   0143   raising and breeding of camels and camelids T...
20   0144   raising of sheep and goats This class exclude...
21   0145   raising of swine/pigs Raising of swine/pigs (...
22   0146   raising of poultry This class excludes: - pro...
23   0149   raising of other animals This class excludes:...
24   0150   mixed farming This class includes the combine...
25   0161   Support activities for crop production This c...
26   0162   Support activities for animal production This...
27   0163   post-harvest crop activities This class exclu...
28   0164   Seed processing for propagation This class in...
29   0170   hunting, trapping and related service activit...
..    ...                                                ...
385  9000   Dramatic arts, music and other arts activitie...
386  9101   library and archives activities This class in...
387  9102   museums activities and operation of historica...
388  9103   botanical and zoological gardens and nature r...
389  9200   Gambling and betting activities This class in...
390  9311   operation of sports facilities This class inc...
391  9312   activities of sports clubs This class include...
392  9319   other sports activities This class includes a...
393  9321   activities of amusement parks and theme parks...
394  9329   other amusement and recreation activities n.e...
395  9411   activities of business and employers membersh...
396  9412   activities of professional membership organiz...
397  9420   activities of trade unions This class include...
398  9491   activities of religious organizations This cl...
399  9499   activities of other membership organizations ...
400  9511   repair of computers and peripheral equipment ...
401  9512   repair of communication equipment This class ...
402  9521   repair of consumer electronics This class inc...
403  9522   repair of household appliances and home and g...
404  9523   repair of footwear and leather goods Repair o...
405  9524   repair of furniture and home furnishings Repa...
406  9529   repair of personal and household goods, n.e.c...
407  9601   Washing and (dry-) cleaning of textile and fu...
408  9602   hairdressing and other beauty treatment This ...
409  9603   Funeral and related activities This class inc...
410  9609   other personal service activities n.e.c. Soci...
411  9700   activities of households as employers of dome...
412  9810   undifferentiated goods-producing activities o...
413  9820   undifferentiated service-producing activities...
414  9900   activities of extraterritorial organizations ...

[415 rows x 2 columns]

## Creating with only divisions

In [40]:
nic_df_division = nic_df_group.copy()

In [41]:
def stripto2(arr):
    return arr[:2]

In [42]:
nic_df_division ['division'] = nic_df_division['group'].apply(stripto2)

In [43]:
nic_df_division.drop('group',axis = 1,inplace=True)
nic_df_division

details division
0     Growing of non-perennial crops Growing of cer...       01
1     Growing of perennial crops Growing of grapes ...       01
2     plant propagation plant propagation This clas...       01
3     animal production raising of cattle and buffa...       01
4     mixed farming mixed farming This class includ...       01
5     Support activities to agriculture and post-ha...       01
6     hunting, trapping and related service activit...       01
7     Silviculture and other forestry activities Si...       02
8     logging logging This class excludes: - growin...       02
9     Gathering of non-wood forest products Gatheri...       02
10    Support services to forestry Support services...       02
11    Fishing Marine fishing This class excludes: #...       03
12    aquaculture marine aquaculture This class exc...       03
13    mining of hard coal mining of hard coal This ...       05
14    mining of lignite mining of lignite This clas...       05
15    extraction of crude petroleum extraction of c...       06
16    extraction of natural gas extraction of natur...       06
17    mining of iron ores mining of iron ores This ...       07
18    mining of non-ferrous metal ores mining of ur...       07
19    quarrying of stone, sand and clay quarrying o...       08
20    mining and quarrying n.e.c. mining of chemica...       08
21    Support activities for petroleum and natural ...       09
22    Support activities for other mining and quarr...       09
23    Processing and preserving of meat processing ...       10
24    Processing and preserving of fish, crustacean...       10
25    processing and preserving of fruit and vegeta...       10
26    manufacture of vegetable and animal oils and ...       10
27    manufacture of dairy products manufacture of ...       10
28    manufacture of grain mill products, starches ...       10
29    manufacture of other food products manufactur...       10
..                                                 ...      ...
208   Compulsory social security activities Compuls...       84
209   primary education primary education Pre-prima...       85
210   Secondary education General secondary educati...       85
211   higher education higher education Higher educ...       85
212   other education Sports and recreation educati...       85
213   educational support services educational supp...       85
214   hospital activities hospital activities This ...       86
215   medical and dental practice activities medica...       86
216   other human health activities other human hea...       86
217   nursing care facilities nursing care faciliti...       87
218   residential care activities for mental retard...       87
219   residential care activities for the elderly a...       87
220   other residential care activities n.e.c. othe...       87
221   Social work activities without accommodation ...       88
222   other social work activities without accommod...       88
223   Creative, arts and entertainment activities D...       90
224   libraries, archives, museums and other cultur...       91
225   Gambling and betting activities Gambling and ...       92
226   Sports activities operation of sports facilit...       93
227   other amusement and recreation activities act...       93
228   activities of business, employers and profess...       94
229   activities of trade unions activities of trad...       94
230   activities of other membership organizations ...       94
231   repair of computers and communication equipme...       95
232   repair of personal and household goods repair...       95
233   other personal service activities Washing and...       96
234   activities of households as employers of dome...       97
235   undifferentiated goods-producing activities o...       98
236   undifferentiated service-producing activities...       98
237   activities of extraterritorial organizations ...       99

[238 rows x 2 columns]

In [44]:
nic_df_division = nic_df_division.groupby('division').agg(lambda x:list(x))
nic_df_division.reset_index(inplace=True)

In [45]:
# nic_df_division['details'][20:40]
nic_df_division

division                                            details
0        01  [ Growing of non-perennial crops Growing of ce...
1        02  [ Silviculture and other forestry activities S...
2        03  [ Fishing Marine fishing This class excludes: ...
3        05  [ mining of hard coal mining of hard coal This...
4        06  [ extraction of crude petroleum extraction of ...
5        07  [ mining of iron ores mining of iron ores This...
6        08  [ quarrying of stone, sand and clay quarrying ...
7        09  [ Support activities for petroleum and natural...
8        10  [ Processing and preserving of meat processing...
9        11  [ manufacture of beverages Distilling, rectify...
10       12  [ manufacture of tobacco products manufacture ...
11       13  [ Spinning, weaving and finishing of textiles ...
12       14  [ manufacture of wearing apparel, except fur a...
13       15  [ tanning and dressing of leather; manufacture...
14       16  [ Saw milling and planing of wood Saw milling ...
15       17  [ manufacture of paper and paper products manu...
16       18  [ printing and service activities related to p...
17       19  [ manufacture of coke oven products manufactur...
18       20  [ manufacture of basic chemicals, fertilizer a...
19       21  [ manufacture of pharmaceuticals, medicinal ch...
20       22  [ manufacture of rubber products manufacture o...
21       23  [ manufacture of glass and glass products manu...
22       24  [ manufacture of basic iron and steel manufact...
23       25  [ manufacture of structural metal products, ta...
24       26  [ manufacture of electronic components manufac...
25       27  [ manufacture of electric motors, generators, ...
26       28  [ manufacture of general purpose machinery man...
27       29  [ manufacture of motor vehicles manufacture of...
28       30  [ building of ships and boats Building of ship...
29       31  [ manufacture of furniture manufacture of furn...
..      ...                                                ...
58       66  [ Activities auxiliary to financial service ac...
59       68  [ real estate activities with own or leased pr...
60       69  [ legal activities legal activities This class...
61       70  [ Activities of head offices Activities of hea...
62       71  [ architectural and engineering activities and...
63       72  [ research and experimental developmenton natu...
64       73  [ advertising advertising This class includes ...
65       74  [ Specialized design activities Specialized de...
66       75  [ veterinary activities veterinary activities ...
67       77  [ renting and leasing of motor vehicles rentin...
68       78  [ activities of employment placement agencies ...
69       79  [ travel agency and tour operator activities t...
70       80  [ private security activities private security...
71       81  [ Combined facilities support activities Combi...
72       82  [ Office administrative and support activities...
73       84  [ administration of the State and the economic...
74       85  [ primary education primary education Pre-prim...
75       86  [ hospital activities hospital activities This...
76       87  [ nursing care facilities nursing care facilit...
77       88  [ Social work activities without accommodation...
78       90  [ Creative, arts and entertainment activities ...
79       91  [ libraries, archives, museums and other cultu...
80       92  [ Gambling and betting activities Gambling and...
81       93  [ Sports activities operation of sports facili...
82       94  [ activities of business, employers and profes...
83       95  [ repair of computers and communication equipm...
84       96  [ other personal service activities Washing an...
85       97  [ activities of households as employers of dom...
86       98  [ undifferentiated goods-producing activities ...
87       99  [ activities of extraterritorial organizations...

[88 rows x 2 columns]

In [46]:
nic_df_division['details'] = nic_df_division['details'].apply(dearray)
nic_df_division

division                                            details
0        01    Growing of non-perennial crops Growing of ce...
1        02    Silviculture and other forestry activities S...
2        03    Fishing Marine fishing This class excludes: ...
3        05    mining of hard coal mining of hard coal This...
4        06    extraction of crude petroleum extraction of ...
5        07    mining of iron ores mining of iron ores This...
6        08    quarrying of stone, sand and clay quarrying ...
7        09    Support activities for petroleum and natural...
8        10    Processing and preserving of meat processing...
9        11    manufacture of beverages Distilling, rectify...
10       12    manufacture of tobacco products manufacture ...
11       13    Spinning, weaving and finishing of textiles ...
12       14    manufacture of wearing apparel, except fur a...
13       15    tanning and dressing of leather; manufacture...
14       16    Saw milling and planing of wood Saw milling ...
15       17    manufacture of paper and paper products manu...
16       18    printing and service activities related to p...
17       19    manufacture of coke oven products manufactur...
18       20    manufacture of basic chemicals, fertilizer a...
19       21    manufacture of pharmaceuticals, medicinal ch...
20       22    manufacture of rubber products manufacture o...
21       23    manufacture of glass and glass products manu...
22       24    manufacture of basic iron and steel manufact...
23       25    manufacture of structural metal products, ta...
24       26    manufacture of electronic components manufac...
25       27    manufacture of electric motors, generators, ...
26       28    manufacture of general purpose machinery man...
27       29    manufacture of motor vehicles manufacture of...
28       30    building of ships and boats Building of ship...
29       31    manufacture of furniture manufacture of furn...
..      ...                                                ...
58       66    Activities auxiliary to financial service ac...
59       68    real estate activities with own or leased pr...
60       69    legal activities legal activities This class...
61       70    Activities of head offices Activities of hea...
62       71    architectural and engineering activities and...
63       72    research and experimental developmenton natu...
64       73    advertising advertising This class includes ...
65       74    Specialized design activities Specialized de...
66       75    veterinary activities veterinary activities ...
67       77    renting and leasing of motor vehicles rentin...
68       78    activities of employment placement agencies ...
69       79    travel agency and tour operator activities t...
70       80    private security activities private security...
71       81    Combined facilities support activities Combi...
72       82    Office administrative and support activities...
73       84    administration of the State and the economic...
74       85    primary education primary education Pre-prim...
75       86    hospital activities hospital activities This...
76       87    nursing care facilities nursing care facilit...
77       88    Social work activities without accommodation...
78       90    Creative, arts and entertainment activities ...
79       91    libraries, archives, museums and other cultu...
80       92    Gambling and betting activities Gambling and...
81       93    Sports activities operation of sports facili...
82       94    activities of business, employers and profes...
83       95    repair of computers and communication equipm...
84       96    other personal service activities Washing an...
85       97    activities of households as employers of dom...
86       98    undifferentiated goods-producing activities ...
87       99    activities of extraterritorial organizations...

[88 rows x 2 columns]

In [47]:
pd.read_csv?

In [48]:
### giving names to divisions, right now it has description but not name
div_names_df = pd.read_csv('division-csv.csv',header = None,names=['name','deets','column2','column3'])
div_names_df['column2'][0] = np.nan
div_names_df['column3'][0]=np.nan
div_names_df

name                                              deets  \
0     Section A                  Agriculture, forestry and fishing   
1   Division 01  Crop and animal production, hunting and relate...   
2   Division 02                               Forestry and logging   
3   Division 03                            Fishing and aquaculture   
4   Division 05                         Mining of coal and lignite   
5   Division 06      Extraction of crude petroleum and natural gas   
6   Division 07                               Mining of metal ores   
7   Division 08                         Other mining and quarrying   
8   Division 09                  Mining support service activities   
9   Division 10                       Manufacture of food products   
10  Division 11                           Manufacture of beverages   
11  Division 12                    Manufacture of tobacco products   
12  Division 13                            Manufacture of textiles   
13  Division 14                     Manufacture of wearing apparel   
14  Division 15        Manufacture of leather and related products   
15  Division 16  Manufacture of wood and products of wood and c...   
16          NaN  manufacture of articles of straw and plaiting ...   
17  Division 17            Manufacture of paper and paper products   
18  Division 18        Printing and reproduction of recorded media   
19  Division 19  Manufacture of coke and refined petroleum prod...   
20  Division 20     Manufacture of chemicals and chemical products   
21  Division 21  Manufacture of pharmaceuticals, medicinal chem...   
22  Division 22        Manufacture of rubber and plastics products   
23  Division 23  Manufacture of other non-metallic mineral prod...   
24  Division 24                        Manufacture of basic metals   
25  Division 25  Manufacture of fabricated metal products, exce...   
26  Division 26  Manufacture of computer, electronic and optica...   
27  Division 27                Manufacture of electrical equipment   
28  Division 28      Manufacture of machinery and equipment n.e.c.   
29  Division 29  Manufacture of motor vehicles, trailers and se...   
..          ...                                                ...   
63  Division 68                             Real estate activities   
64  Division 69                    Legal and accounting activities   
65  Division 70  Activities of head offices; management consult...   
66  Division 71  Architecture and engineering activities; techn...   
67  Division 72                Scientific research and development   
68  Division 73                    Advertising and market research   
69  Division 74  Other professional, scientific and technical a...   
70  Division 75                              Veterinary activities   
71  Division 77                      Rental and leasing activities   
72  Division 78                              Employment activities   
73  Division 79  Travel agency, tour operator and other reserva...   
74  Division 80              Security and investigation activities   
75  Division 81     Services to buildings and landscape activities   
76  Division 82  Office administrative, office support and othe...   
77  Division 84  Public administration and defence; compulsory ...   
78  Division 85                                          Education   
79  Division 86                            Human health activities   
80  Division 87                        Residential care activities   
81  Division 88       Social work activities without accommodation   
82  Division 90        Creative, arts and entertainment activities   
83  Division 91  Libraries, archives, museums and other cultura...   
84  Division 92                    Gambling and betting activities   
85  Division 93  Sports activities and amusement and recreation...   
86  Division 94             Activities of membership organizations   
87  Division 95  Repair of computers and personal and household...   
88  Division 96      

In [49]:
div_names_df.fillna('',inplace=True)
div_names_df

name                                              deets  \
0     Section A                  Agriculture, forestry and fishing   
1   Division 01  Crop and animal production, hunting and relate...   
2   Division 02                               Forestry and logging   
3   Division 03                            Fishing and aquaculture   
4   Division 05                         Mining of coal and lignite   
5   Division 06      Extraction of crude petroleum and natural gas   
6   Division 07                               Mining of metal ores   
7   Division 08                         Other mining and quarrying   
8   Division 09                  Mining support service activities   
9   Division 10                       Manufacture of food products   
10  Division 11                           Manufacture of beverages   
11  Division 12                    Manufacture of tobacco products   
12  Division 13                            Manufacture of textiles   
13  Division 14                     Manufacture of wearing apparel   
14  Division 15        Manufacture of leather and related products   
15  Division 16  Manufacture of wood and products of wood and c...   
16               manufacture of articles of straw and plaiting ...   
17  Division 17            Manufacture of paper and paper products   
18  Division 18        Printing and reproduction of recorded media   
19  Division 19  Manufacture of coke and refined petroleum prod...   
20  Division 20     Manufacture of chemicals and chemical products   
21  Division 21  Manufacture of pharmaceuticals, medicinal chem...   
22  Division 22        Manufacture of rubber and plastics products   
23  Division 23  Manufacture of other non-metallic mineral prod...   
24  Division 24                        Manufacture of basic metals   
25  Division 25  Manufacture of fabricated metal products, exce...   
26  Division 26  Manufacture of computer, electronic and optica...   
27  Division 27                Manufacture of electrical equipment   
28  Division 28      Manufacture of machinery and equipment n.e.c.   
29  Division 29  Manufacture of motor vehicles, trailers and se...   
..          ...                                                ...   
63  Division 68                             Real estate activities   
64  Division 69                    Legal and accounting activities   
65  Division 70  Activities of head offices; management consult...   
66  Division 71  Architecture and engineering activities; techn...   
67  Division 72                Scientific research and development   
68  Division 73                    Advertising and market research   
69  Division 74  Other professional, scientific and technical a...   
70  Division 75                              Veterinary activities   
71  Division 77                      Rental and leasing activities   
72  Division 78                              Employment activities   
73  Division 79  Travel agency, tour operator and other reserva...   
74  Division 80              Security and investigation activities   
75  Division 81     Services to buildings and landscape activities   
76  Division 82  Office administrative, office support and othe...   
77  Division 84  Public administration and defence; compulsory ...   
78  Division 85                                          Education   
79  Division 86                            Human health activities   
80  Division 87                        Residential care activities   
81  Division 88       Social work activities without accommodation   
82  Division 90        Creative, arts and entertainment activities   
83  Division 91  Libraries, archives, museums and other cultura...   
84  Division 92                    Gambling and betting activities   
85  Division 93  Sports activities and amusement and recreation...   
86  Division 94             Activities of membership organizations   
87  Division 95  Repair of computers and personal and household...   
88  Division 96      

In [50]:
div_names_df['deets'] = div_names_df['deets']+div_names_df['column2']+div_names_df['column3']
div_names_df.drop(['column2','column3'],axis =1,inplace=True)
div_names_df

name                                              deets
0     Section A                  Agriculture, forestry and fishing
1   Division 01  Crop and animal production, hunting and relate...
2   Division 02                               Forestry and logging
3   Division 03                            Fishing and aquaculture
4   Division 05                         Mining of coal and lignite
5   Division 06      Extraction of crude petroleum and natural gas
6   Division 07                               Mining of metal ores
7   Division 08                         Other mining and quarrying
8   Division 09                  Mining support service activities
9   Division 10                       Manufacture of food products
10  Division 11                           Manufacture of beverages
11  Division 12                    Manufacture of tobacco products
12  Division 13                            Manufacture of textiles
13  Division 14                     Manufacture of wearing apparel
14  Division 15        Manufacture of leather and related products
15  Division 16  Manufacture of wood and products of wood and c...
16               manufacture of articles of straw and plaiting ...
17  Division 17            Manufacture of paper and paper products
18  Division 18        Printing and reproduction of recorded media
19  Division 19  Manufacture of coke and refined petroleum prod...
20  Division 20     Manufacture of chemicals and chemical products
21  Division 21  Manufacture of pharmaceuticals, medicinal chem...
22  Division 22        Manufacture of rubber and plastics products
23  Division 23  Manufacture of other non-metallic mineral prod...
24  Division 24                        Manufacture of basic metals
25  Division 25  Manufacture of fabricated metal products, exce...
26  Division 26  Manufacture of computer, electronic and optica...
27  Division 27                Manufacture of electrical equipment
28  Division 28      Manufacture of machinery and equipment n.e.c.
29  Division 29  Manufacture of motor vehicles, trailers and se...
..          ...                                                ...
63  Division 68                             Real estate activities
64  Division 69                    Legal and accounting activities
65  Division 70  Activities of head offices; management consult...
66  Division 71  Architecture and engineering activities; techn...
67  Division 72                Scientific research and development
68  Division 73                    Advertising and market research
69  Division 74  Other professional, scientific and technical a...
70  Division 75                              Veterinary activities
71  Division 77                      Rental and leasing activities
72  Division 78                              Employment activities
73  Division 79  Travel agency, tour operator and other reserva...
74  Division 80              Security and investigation activities
75  Division 81     Services to buildings and landscape activities
76  Division 82  Office administrative, office support and othe...
77  Division 84  Public administration and defence; compulsory ...
78  Division 85                                          Education
79  Division 86                            Human health activities
80  Division 87                        Residential care activities
81  Division 88       Social work activities without accommodation
82  Division 90        Creative, arts and entertainment activities
83  Division 91  Libraries, archives, museums and other cultura...
84  Division 92                    Gambling and betting activities
85  Division 93  Sports activities and amusement and recreation...
86  Division 94             Activities of membership organizations
87  Division 95  Repair of computers and personal and household...
88  Division 96                  Other personal service activities
89  Division 97  Activities of households as employers of domes...
90  Division 98  Undifferentiated goods- and services-prod

In [51]:
div_names_df.drop([0],inplace=True)
div_names_df

name                                              deets
1   Division 01  Crop and animal production, hunting and relate...
2   Division 02                               Forestry and logging
3   Division 03                            Fishing and aquaculture
4   Division 05                         Mining of coal and lignite
5   Division 06      Extraction of crude petroleum and natural gas
6   Division 07                               Mining of metal ores
7   Division 08                         Other mining and quarrying
8   Division 09                  Mining support service activities
9   Division 10                       Manufacture of food products
10  Division 11                           Manufacture of beverages
11  Division 12                    Manufacture of tobacco products
12  Division 13                            Manufacture of textiles
13  Division 14                     Manufacture of wearing apparel
14  Division 15        Manufacture of leather and related products
15  Division 16  Manufacture of wood and products of wood and c...
16               manufacture of articles of straw and plaiting ...
17  Division 17            Manufacture of paper and paper products
18  Division 18        Printing and reproduction of recorded media
19  Division 19  Manufacture of coke and refined petroleum prod...
20  Division 20     Manufacture of chemicals and chemical products
21  Division 21  Manufacture of pharmaceuticals, medicinal chem...
22  Division 22        Manufacture of rubber and plastics products
23  Division 23  Manufacture of other non-metallic mineral prod...
24  Division 24                        Manufacture of basic metals
25  Division 25  Manufacture of fabricated metal products, exce...
26  Division 26  Manufacture of computer, electronic and optica...
27  Division 27                Manufacture of electrical equipment
28  Division 28      Manufacture of machinery and equipment n.e.c.
29  Division 29  Manufacture of motor vehicles, trailers and se...
30  Division 30           Manufacture of other transport equipment
..          ...                                                ...
63  Division 68                             Real estate activities
64  Division 69                    Legal and accounting activities
65  Division 70  Activities of head offices; management consult...
66  Division 71  Architecture and engineering activities; techn...
67  Division 72                Scientific research and development
68  Division 73                    Advertising and market research
69  Division 74  Other professional, scientific and technical a...
70  Division 75                              Veterinary activities
71  Division 77                      Rental and leasing activities
72  Division 78                              Employment activities
73  Division 79  Travel agency, tour operator and other reserva...
74  Division 80              Security and investigation activities
75  Division 81     Services to buildings and landscape activities
76  Division 82  Office administrative, office support and othe...
77  Division 84  Public administration and defence; compulsory ...
78  Division 85                                          Education
79  Division 86                            Human health activities
80  Division 87                        Residential care activities
81  Division 88       Social work activities without accommodation
82  Division 90        Creative, arts and entertainment activities
83  Division 91  Libraries, archives, museums and other cultura...
84  Division 92                    Gambling and betting activities
85  Division 93  Sports activities and amusement and recreation...
86  Division 94             Activities of membership organizations
87  Division 95  Repair of computers and personal and household...
88  Division 96                  Other personal service activities
89  Division 97  Activities of households as employers of domes...
90  Division 98  Undifferentiated goods- and services-prod

In [52]:
def stripdivname(arr):
    if arr !='':
        return arr.strip().split()[-1]

In [53]:
'Dvision 01'.strip().split()[-1]

'01'

In [54]:
div_names_df['codes'] = div_names_df['name'].apply(stripdivname)
div_names_df['codes'] = div_names_df['codes'].ffill()

In [55]:
div_names_df.drop('name',axis=1,inplace=True)
div_names_df

deets codes
1   Crop and animal production, hunting and relate...    01
2                                Forestry and logging    02
3                             Fishing and aquaculture    03
4                          Mining of coal and lignite    05
5       Extraction of crude petroleum and natural gas    06
6                                Mining of metal ores    07
7                          Other mining and quarrying    08
8                   Mining support service activities    09
9                        Manufacture of food products    10
10                           Manufacture of beverages    11
11                    Manufacture of tobacco products    12
12                            Manufacture of textiles    13
13                     Manufacture of wearing apparel    14
14        Manufacture of leather and related products    15
15  Manufacture of wood and products of wood and c...    16
16  manufacture of articles of straw and plaiting ...    16
17            Manufacture of paper and paper products    17
18        Printing and reproduction of recorded media    18
19  Manufacture of coke and refined petroleum prod...    19
20     Manufacture of chemicals and chemical products    20
21  Manufacture of pharmaceuticals, medicinal chem...    21
22        Manufacture of rubber and plastics products    22
23  Manufacture of other non-metallic mineral prod...    23
24                        Manufacture of basic metals    24
25  Manufacture of fabricated metal products, exce...    25
26  Manufacture of computer, electronic and optica...    26
27                Manufacture of electrical equipment    27
28      Manufacture of machinery and equipment n.e.c.    28
29  Manufacture of motor vehicles, trailers and se...    29
30           Manufacture of other transport equipment    30
..                                                ...   ...
63                             Real estate activities    68
64                    Legal and accounting activities    69
65  Activities of head offices; management consult...    70
66  Architecture and engineering activities; techn...    71
67                Scientific research and development    72
68                    Advertising and market research    73
69  Other professional, scientific and technical a...    74
70                              Veterinary activities    75
71                      Rental and leasing activities    77
72                              Employment activities    78
73  Travel agency, tour operator and other reserva...    79
74              Security and investigation activities    80
75     Services to buildings and landscape activities    81
76  Office administrative, office support and othe...    82
77  Public administration and defence; compulsory ...    84
78                                          Education    85
79                            Human health activities    86
80                        Residential care activities    87
81       Social work activities without accommodation    88
82        Creative, arts and entertainment activities    90
83  Libraries, archives, museums and other cultura...    91
84                    Gambling and betting activities    92
85  Sports activities and amusement and recreation...    93
86             Activities of membership organizations    94
87  Repair of computers and personal and household...    95
88                  Other personal service activities    96
89  Activities of households as employers of domes...    97
90  Undifferentiated goods- and services-producing...    98
91                             households for own use    98
92  Activities of extraterritorial organizations a...    99

[92 rows x 2 columns]

In [56]:
div_names_df = div_names_df.groupby('codes').agg(lambda x:list(x))

In [57]:
div_names_df.reset_index(inplace=True)
div_names_df['deets'] = div_names_df['deets'].apply(dearray)
div_names_df

codes                                              deets
0     01   Crop and animal production, hunting and relat...
1     02                               Forestry and logging
2     03                            Fishing and aquaculture
3     05                         Mining of coal and lignite
4     06      Extraction of crude petroleum and natural gas
5     07                               Mining of metal ores
6     08                         Other mining and quarrying
7     09                  Mining support service activities
8     10                       Manufacture of food products
9     11                           Manufacture of beverages
10    12                    Manufacture of tobacco products
11    13                            Manufacture of textiles
12    14                     Manufacture of wearing apparel
13    15        Manufacture of leather and related products
14    16   Manufacture of wood and products of wood and ...
15    17            Manufacture of paper and paper products
16    18        Printing and reproduction of recorded media
17    19   Manufacture of coke and refined petroleum pro...
18    20     Manufacture of chemicals and chemical products
19    21   Manufacture of pharmaceuticals, medicinal che...
20    22        Manufacture of rubber and plastics products
21    23   Manufacture of other non-metallic mineral pro...
22    24                        Manufacture of basic metals
23    25   Manufacture of fabricated metal products, exc...
24    26   Manufacture of computer, electronic and optic...
25    27                Manufacture of electrical equipment
26    28      Manufacture of machinery and equipment n.e.c.
27    29   Manufacture of motor vehicles, trailers and s...
28    30           Manufacture of other transport equipment
29    31                           Manufacture of furniture
..   ...                                                ...
58    66                         Other financial activities
59    68                             Real estate activities
60    69                    Legal and accounting activities
61    70   Activities of head offices; management consul...
62    71   Architecture and engineering activities; tech...
63    72                Scientific research and development
64    73                    Advertising and market research
65    74   Other professional, scientific and technical ...
66    75                              Veterinary activities
67    77                      Rental and leasing activities
68    78                              Employment activities
69    79   Travel agency, tour operator and other reserv...
70    80              Security and investigation activities
71    81     Services to buildings and landscape activities
72    82   Office administrative, office support and oth...
73    84   Public administration and defence; compulsory...
74    85                                          Education
75    86                            Human health activities
76    87                        Residential care activities
77    88       Social work activities without accommodation
78    90        Creative, arts and entertainment activities
79    91   Libraries, archives, museums and other cultur...
80    92                    Gambling and betting activities
81    93   Sports activities and amusement and recreatio...
82    94             Activities of membership organizations
83    95   Repair of computers and personal and househol...
84    96                  Other personal service activities
85    97   Activities of households as employers of dome...
86    98   Undifferentiated goods- and services-producin...
87    99   Activities of extraterritorial organizations ...

[88 rows x 2 columns]

In [58]:
div_names_df.rename(columns = {'codes':'division'},inplace=True)
div_names_df

division                                              deets
0        01   Crop and animal production, hunting and relat...
1        02                               Forestry and logging
2        03                            Fishing and aquaculture
3        05                         Mining of coal and lignite
4        06      Extraction of crude petroleum and natural gas
5        07                               Mining of metal ores
6        08                         Other mining and quarrying
7        09                  Mining support service activities
8        10                       Manufacture of food products
9        11                           Manufacture of beverages
10       12                    Manufacture of tobacco products
11       13                            Manufacture of textiles
12       14                     Manufacture of wearing apparel
13       15        Manufacture of leather and related products
14       16   Manufacture of wood and products of wood and ...
15       17            Manufacture of paper and paper products
16       18        Printing and reproduction of recorded media
17       19   Manufacture of coke and refined petroleum pro...
18       20     Manufacture of chemicals and chemical products
19       21   Manufacture of pharmaceuticals, medicinal che...
20       22        Manufacture of rubber and plastics products
21       23   Manufacture of other non-metallic mineral pro...
22       24                        Manufacture of basic metals
23       25   Manufacture of fabricated metal products, exc...
24       26   Manufacture of computer, electronic and optic...
25       27                Manufacture of electrical equipment
26       28      Manufacture of machinery and equipment n.e.c.
27       29   Manufacture of motor vehicles, trailers and s...
28       30           Manufacture of other transport equipment
29       31                           Manufacture of furniture
..      ...                                                ...
58       66                         Other financial activities
59       68                             Real estate activities
60       69                    Legal and accounting activities
61       70   Activities of head offices; management consul...
62       71   Architecture and engineering activities; tech...
63       72                Scientific research and development
64       73                    Advertising and market research
65       74   Other professional, scientific and technical ...
66       75                              Veterinary activities
67       77                      Rental and leasing activities
68       78                              Employment activities
69       79   Travel agency, tour operator and other reserv...
70       80              Security and investigation activities
71       81     Services to buildings and landscape activities
72       82   Office administrative, office support and oth...
73       84   Public administration and defence; compulsory...
74       85                                          Education
75       86                            Human health activities
76       87                        Residential care activities
77       88       Social work activities without accommodation
78       90        Creative, arts and entertainment activities
79       91   Libraries, archives, museums and other cultur...
80       92                    Gambling and betting activities
81       93   Sports activities and amusement and recreatio...
82       94             Activities of membership organizations
83       95   Repair of computers and personal and househol...
84       96                  Other personal service activities
85       97   Activities of households as employers of dome...
86       98   Undifferentiated goods- and services-producin...
87       99   Activities of extraterritorial organizations ...

[88 rows x 2 columns]

In [59]:
# pd.merge?
nic_df_division

division                                            details
0        01    Growing of non-perennial crops Growing of ce...
1        02    Silviculture and other forestry activities S...
2        03    Fishing Marine fishing This class excludes: ...
3        05    mining of hard coal mining of hard coal This...
4        06    extraction of crude petroleum extraction of ...
5        07    mining of iron ores mining of iron ores This...
6        08    quarrying of stone, sand and clay quarrying ...
7        09    Support activities for petroleum and natural...
8        10    Processing and preserving of meat processing...
9        11    manufacture of beverages Distilling, rectify...
10       12    manufacture of tobacco products manufacture ...
11       13    Spinning, weaving and finishing of textiles ...
12       14    manufacture of wearing apparel, except fur a...
13       15    tanning and dressing of leather; manufacture...
14       16    Saw milling and planing of wood Saw milling ...
15       17    manufacture of paper and paper products manu...
16       18    printing and service activities related to p...
17       19    manufacture of coke oven products manufactur...
18       20    manufacture of basic chemicals, fertilizer a...
19       21    manufacture of pharmaceuticals, medicinal ch...
20       22    manufacture of rubber products manufacture o...
21       23    manufacture of glass and glass products manu...
22       24    manufacture of basic iron and steel manufact...
23       25    manufacture of structural metal products, ta...
24       26    manufacture of electronic components manufac...
25       27    manufacture of electric motors, generators, ...
26       28    manufacture of general purpose machinery man...
27       29    manufacture of motor vehicles manufacture of...
28       30    building of ships and boats Building of ship...
29       31    manufacture of furniture manufacture of furn...
..      ...                                                ...
58       66    Activities auxiliary to financial service ac...
59       68    real estate activities with own or leased pr...
60       69    legal activities legal activities This class...
61       70    Activities of head offices Activities of hea...
62       71    architectural and engineering activities and...
63       72    research and experimental developmenton natu...
64       73    advertising advertising This class includes ...
65       74    Specialized design activities Specialized de...
66       75    veterinary activities veterinary activities ...
67       77    renting and leasing of motor vehicles rentin...
68       78    activities of employment placement agencies ...
69       79    travel agency and tour operator activities t...
70       80    private security activities private security...
71       81    Combined facilities support activities Combi...
72       82    Office administrative and support activities...
73       84    administration of the State and the economic...
74       85    primary education primary education Pre-prim...
75       86    hospital activities hospital activities This...
76       87    nursing care facilities nursing care facilit...
77       88    Social work activities without accommodation...
78       90    Creative, arts and entertainment activities ...
79       91    libraries, archives, museums and other cultu...
80       92    Gambling and betting activities Gambling and...
81       93    Sports activities operation of sports facili...
82       94    activities of business, employers and profes...
83       95    repair of computers and communication equipm...
84       96    other personal service activities Washing an...
85       97    activities of households as employers of dom...
86       98    undifferentiated goods-producing activities ...
87       99    activities of extraterritorial organizations...

[88 rows x 2 columns]

In [60]:
nic_df_division = pd.merge(nic_df_division,div_names_df,on = 'division' )
nic_df_division.rename(columns = {'deets': 'name'},inplace=True)

In [61]:
nic_df_division

division                                            details  \
0        01    Growing of non-perennial crops Growing of ce...   
1        02    Silviculture and other forestry activities S...   
2        03    Fishing Marine fishing This class excludes: ...   
3        05    mining of hard coal mining of hard coal This...   
4        06    extraction of crude petroleum extraction of ...   
5        07    mining of iron ores mining of iron ores This...   
6        08    quarrying of stone, sand and clay quarrying ...   
7        09    Support activities for petroleum and natural...   
8        10    Processing and preserving of meat processing...   
9        11    manufacture of beverages Distilling, rectify...   
10       12    manufacture of tobacco products manufacture ...   
11       13    Spinning, weaving and finishing of textiles ...   
12       14    manufacture of wearing apparel, except fur a...   
13       15    tanning and dressing of leather; manufacture...   
14       16    Saw milling and planing of wood Saw milling ...   
15       17    manufacture of paper and paper products manu...   
16       18    printing and service activities related to p...   
17       19    manufacture of coke oven products manufactur...   
18       20    manufacture of basic chemicals, fertilizer a...   
19       21    manufacture of pharmaceuticals, medicinal ch...   
20       22    manufacture of rubber products manufacture o...   
21       23    manufacture of glass and glass products manu...   
22       24    manufacture of basic iron and steel manufact...   
23       25    manufacture of structural metal products, ta...   
24       26    manufacture of electronic components manufac...   
25       27    manufacture of electric motors, generators, ...   
26       28    manufacture of general purpose machinery man...   
27       29    manufacture of motor vehicles manufacture of...   
28       30    building of ships and boats Building of ship...   
29       31    manufacture of furniture manufacture of furn...   
..      ...                                                ...   
58       66    Activities auxiliary to financial service ac...   
59       68    real estate activities with own or leased pr...   
60       69    legal activities legal activities This class...   
61       70    Activities of head offices Activities of hea...   
62       71    architectural and engineering activities and...   
63       72    research and experimental developmenton natu...   
64       73    advertising advertising This class includes ...   
65       74    Specialized design activities Specialized de...   
66       75    veterinary activities veterinary activities ...   
67       77    renting and leasing of motor vehicles rentin...   
68       78    activities of employment placement agencies ...   
69       79    travel agency and tour operator activities t...   
70       80    private security activities private security...   
71       81    Combined facilities support activities Combi...   
72       82    Office administrative and support activities...   
73       84    administration of the State and the economic...   
74       85    primary education primary education Pre-prim...   
75       86    hospital activities hospital activities This...   
76       87    nursing care facilities nursing care facilit...   
77       88    Social work activities without accommodation...   
78       90    Creative, arts and entertainment activities ...   
79       91    libraries, archives, museums and other cultu...   
80       92    Gambling and betting activities Gambling and...   
81       93    Sports activities operation of sports facili...   
82       94    activities of business, employers and profes...   
83       95    repair of computers and communication equipm...   
84       96    other personal service activities Washing an...   
85       97    activities of households as employers of dom...   
86       98    undifferentiated goods-produ

# now sectionwise

In [62]:
# div_sec_dict = nic_df_division['division'].to_csv('div_sec_dict1.csv')
# i have used itto manually fill startig entries of sections.

In [63]:
div_sec_dict = pd.read_csv('div_sec_dict.csv',header = None,names= ['division','section'])
div_sec_dict['section'].ffill(inplace=True)

In [64]:
div_sec_dict

division section
0          1       A
1          2       A
2          3       A
3          5       B
4          6       B
5          7       B
6          8       B
7          9       B
8         10       C
9         11       C
10        12       C
11        13       C
12        14       C
13        15       C
14        16       C
15        17       C
16        18       C
17        19       C
18        20       C
19        21       C
20        22       C
21        23       C
22        24       C
23        25       C
24        26       C
25        27       C
26        28       C
27        29       C
28        30       C
29        31       C
..       ...     ...
58        66       K
59        68       L
60        69       M
61        70       M
62        71       M
63        72       M
64        73       M
65        74       M
66        75       M
67        77       N
68        78       N
69        79       N
70        80       N
71        81       N
72        82       N
73        84       O
74        85       P
75        86       Q
76        87       Q
77        88       Q
78        90       R
79        91       R
80        92       R
81        93       R
82        94       S
83        95       S
84        96       S
85        97       T
86        98       T
87        99       U

[88 rows x 2 columns]

### for section names

In [65]:
sect_names =pd.read_csv('sections.csv',header=None,names=['section','deets'])

In [66]:
# sect_names['section'].ffill(inplace=True)

In [67]:
sect_names

section                                              deets
0   Section A                  Agriculture, forestry and fishing
1   Section B                               Mining and quarrying
2   Section C                                      Manufacturing
3   Section D  Electricity, gas, steam and air conditioning s...
4   Section E  Water supply; sewerage, waste management and r...
5   Section F                                       Construction
6   Section G  Wholesale and retail trade; repair of motor ve...
7   Section H                         Transportation and storage
8   Section I          Accommodation and Food service activities
9   Section J                      Information and communication
10  Section K                 Financial and insurance activities
11  Section L                             Real estate activities
12  Section M  Professional, scientific and technical activities
13  Section N      Administrative and support service activities
14  Section O  Public administration and defence; compulsory ...
15  Section P                                          Education
16  Section Q            Human health and social work activities
17  Section R                 Arts, entertainment and recreation
18  Section S                           Other service activities
19  Section T  Activities of households as employers; undiffe...
20  Section U  Activities of extraterritorial organizations a...

In [68]:
sect_names['section'] = pd.Series(map(lambda x: x.strip().split()[-1],sect_names['section']))

In [69]:
sect_names

section                                              deets
0        A                  Agriculture, forestry and fishing
1        B                               Mining and quarrying
2        C                                      Manufacturing
3        D  Electricity, gas, steam and air conditioning s...
4        E  Water supply; sewerage, waste management and r...
5        F                                       Construction
6        G  Wholesale and retail trade; repair of motor ve...
7        H                         Transportation and storage
8        I          Accommodation and Food service activities
9        J                      Information and communication
10       K                 Financial and insurance activities
11       L                             Real estate activities
12       M  Professional, scientific and technical activities
13       N      Administrative and support service activities
14       O  Public administration and defence; compulsory ...
15       P                                          Education
16       Q            Human health and social work activities
17       R                 Arts, entertainment and recreation
18       S                           Other service activities
19       T  Activities of households as employers; undiffe...
20       U  Activities of extraterritorial organizations a...

In [70]:
sect_df =nic_df_division.copy()

In [71]:
sect_df['division'] = pd.to_numeric(sect_df['division'],downcast = 'integer',errors = 'ignore')
sect_df

division                                            details  \
0          1    Growing of non-perennial crops Growing of ce...   
1          2    Silviculture and other forestry activities S...   
2          3    Fishing Marine fishing This class excludes: ...   
3          5    mining of hard coal mining of hard coal This...   
4          6    extraction of crude petroleum extraction of ...   
5          7    mining of iron ores mining of iron ores This...   
6          8    quarrying of stone, sand and clay quarrying ...   
7          9    Support activities for petroleum and natural...   
8         10    Processing and preserving of meat processing...   
9         11    manufacture of beverages Distilling, rectify...   
10        12    manufacture of tobacco products manufacture ...   
11        13    Spinning, weaving and finishing of textiles ...   
12        14    manufacture of wearing apparel, except fur a...   
13        15    tanning and dressing of leather; manufacture...   
14        16    Saw milling and planing of wood Saw milling ...   
15        17    manufacture of paper and paper products manu...   
16        18    printing and service activities related to p...   
17        19    manufacture of coke oven products manufactur...   
18        20    manufacture of basic chemicals, fertilizer a...   
19        21    manufacture of pharmaceuticals, medicinal ch...   
20        22    manufacture of rubber products manufacture o...   
21        23    manufacture of glass and glass products manu...   
22        24    manufacture of basic iron and steel manufact...   
23        25    manufacture of structural metal products, ta...   
24        26    manufacture of electronic components manufac...   
25        27    manufacture of electric motors, generators, ...   
26        28    manufacture of general purpose machinery man...   
27        29    manufacture of motor vehicles manufacture of...   
28        30    building of ships and boats Building of ship...   
29        31    manufacture of furniture manufacture of furn...   
..       ...                                                ...   
58        66    Activities auxiliary to financial service ac...   
59        68    real estate activities with own or leased pr...   
60        69    legal activities legal activities This class...   
61        70    Activities of head offices Activities of hea...   
62        71    architectural and engineering activities and...   
63        72    research and experimental developmenton natu...   
64        73    advertising advertising This class includes ...   
65        74    Specialized design activities Specialized de...   
66        75    veterinary activities veterinary activities ...   
67        77    renting and leasing of motor vehicles rentin...   
68        78    activities of employment placement agencies ...   
69        79    travel agency and tour operator activities t...   
70        80    private security activities private security...   
71        81    Combined facilities support activities Combi...   
72        82    Office administrative and support activities...   
73        84    administration of the State and the economic...   
74        85    primary education primary education Pre-prim...   
75        86    hospital activities hospital activities This...   
76        87    nursing care facilities nursing care facilit...   
77        88    Social work activities without accommodation...   
78        90    Creative, arts and entertainment activities ...   
79        91    libraries, archives, museums and other cultu...   
80        92    Gambling and betting activities Gambling and...   
81        93    Sports activities operation of sports facili...   
82        94    activities of business, employers and profes...   
83        95    repair of computers and communication equipm...   
84        96    other personal service activities Washing an...   
85        97    activities of households as employe

In [72]:
# pd.to_dict()?
# div_sec_dict

In [73]:
div_sec_dict.set_index('division',inplace=True)
div_sec_dict

section
division        
1              A
2              A
3              A
5              B
6              B
7              B
8              B
9              B
10             C
11             C
12             C
13             C
14             C
15             C
16             C
17             C
18             C
19             C
20             C
21             C
22             C
23             C
24             C
25             C
26             C
27             C
28             C
29             C
30             C
31             C
...          ...
66             K
68             L
69             M
70             M
71             M
72             M
73             M
74             M
75             M
77             N
78             N
79             N
80             N
81             N
82             N
84             O
85             P
86             Q
87             Q
88             Q
90             R
91             R
92             R
93             R
94             S
95             S
96             S
97             T
98             T
99             U

[88 rows x 1 columns]

In [74]:
divsecdict = div_sec_dict.to_dict('index')
divsecdict

{1: {'section': 'A'},
 2: {'section': 'A'},
 3: {'section': 'A'},
 5: {'section': 'B'},
 6: {'section': 'B'},
 7: {'section': 'B'},
 8: {'section': 'B'},
 9: {'section': 'B'},
 10: {'section': 'C'},
 11: {'section': 'C'},
 12: {'section': 'C'},
 13: {'section': 'C'},
 14: {'section': 'C'},
 15: {'section': 'C'},
 16: {'section': 'C'},
 17: {'section': 'C'},
 18: {'section': 'C'},
 19: {'section': 'C'},
 20: {'section': 'C'},
 21: {'section': 'C'},
 22: {'section': 'C'},
 23: {'section': 'C'},
 24: {'section': 'C'},
 25: {'section': 'C'},
 26: {'section': 'C'},
 27: {'section': 'C'},
 28: {'section': 'C'},
 29: {'section': 'C'},
 30: {'section': 'C'},
 31: {'section': 'C'},
 32: {'section': 'C'},
 33: {'section': 'C'},
 35: {'section': 'D'},
 36: {'section': 'E'},
 37: {'section': 'E'},
 38: {'section': 'E'},
 39: {'section': 'E'},
 41: {'section': 'F'},
 42: {'section': 'F'},
 43: {'section': 'F'},
 45: {'section': 'G'},
 46: {'section': 'G'},
 47: {'section': 'G'},
 49: {'section': 'H

In [75]:
div_sec_dict.to_dict('index')[1]['section']

'A'

In [76]:
sect_df['section'] = pd.Series(map(lambda x:div_sec_dict.to_dict('index')[x]['section'], sect_df['division']))
sect_df['details'] = sect_df['details']+sect_df['name'] #divisions name can be used as description to section
sect_df.drop('name',axis=1,inplace=True)
sect_df

division                                            details section
0          1    Growing of non-perennial crops Growing of ce...       A
1          2    Silviculture and other forestry activities S...       A
2          3    Fishing Marine fishing This class excludes: ...       A
3          5    mining of hard coal mining of hard coal This...       B
4          6    extraction of crude petroleum extraction of ...       B
5          7    mining of iron ores mining of iron ores This...       B
6          8    quarrying of stone, sand and clay quarrying ...       B
7          9    Support activities for petroleum and natural...       B
8         10    Processing and preserving of meat processing...       C
9         11    manufacture of beverages Distilling, rectify...       C
10        12    manufacture of tobacco products manufacture ...       C
11        13    Spinning, weaving and finishing of textiles ...       C
12        14    manufacture of wearing apparel, except fur a...       C
13        15    tanning and dressing of leather; manufacture...       C
14        16    Saw milling and planing of wood Saw milling ...       C
15        17    manufacture of paper and paper products manu...       C
16        18    printing and service activities related to p...       C
17        19    manufacture of coke oven products manufactur...       C
18        20    manufacture of basic chemicals, fertilizer a...       C
19        21    manufacture of pharmaceuticals, medicinal ch...       C
20        22    manufacture of rubber products manufacture o...       C
21        23    manufacture of glass and glass products manu...       C
22        24    manufacture of basic iron and steel manufact...       C
23        25    manufacture of structural metal products, ta...       C
24        26    manufacture of electronic components manufac...       C
25        27    manufacture of electric motors, generators, ...       C
26        28    manufacture of general purpose machinery man...       C
27        29    manufacture of motor vehicles manufacture of...       C
28        30    building of ships and boats Building of ship...       C
29        31    manufacture of furniture manufacture of furn...       C
..       ...                                                ...     ...
58        66    Activities auxiliary to financial service ac...       K
59        68    real estate activities with own or leased pr...       L
60        69    legal activities legal activities This class...       M
61        70    Activities of head offices Activities of hea...       M
62        71    architectural and engineering activities and...       M
63        72    research and experimental developmenton natu...       M
64        73    advertising advertising This class includes ...       M
65        74    Specialized design activities Specialized de...       M
66        75    veterinary activities veterinary activities ...       M
67        77    renting and leasing of motor vehicles rentin...       N
68        78    activities of employment placement agencies ...       N
69        79    travel agency and tour operator activities t...       N
70        80    private security activities private security...       N
71        81    Combined facilities support activities Combi...       N
72        82    Office administrative and support activities...       N
73        84    administration of the State and the economic...       O
74        85    primary education primary education Pre-prim...       P
75        86    hospital activities hospital activities This...       Q
76        87    nursing care facilities nursing care facilit...       Q
77        88    Social work activities without accommodation...       Q
78        90    Creative, arts and entertainment activities ...       R
79        91    libraries, archives, museums and other cultu...       R
80        92    Gambling and betting activities Gambling and...       R
81        93    Sports activities operation 

In [77]:
sect_df.drop('division',axis=1,inplace=True)
sect_df = sect_df.groupby('section').agg(lambda x:list(x))
sect_df['details'] = sect_df['details'] .apply(dearray)
sect_df.reset_index(inplace=True)
sect_df

section                                            details
0        A     Growing of non-perennial crops Growing of c...
1        B     mining of hard coal mining of hard coal Thi...
2        C     Processing and preserving of meat processin...
3        D     electric power generation, transmission and...
4        E     Water collection, treatment and supply Wate...
5        F     Construction of buildings Construction of b...
6        G     Sale of motor vehicles Sale of motor vehicl...
7        H     transport via railways passenger rail trans...
8        I     Short term accommodation activities Short t...
9        J     publishing of books, periodicals and other ...
10       K     monetary intermediation Central banking Thi...
11       L     real estate activities with own or leased p...
12       M     legal activities legal activities This clas...
13       N     renting and leasing of motor vehicles renti...
14       O     administration of the State and the economi...
15       P     primary education primary education Pre-pri...
16       Q     hospital activities hospital activities Thi...
17       R     Creative, arts and entertainment activities...
18       S     activities of business, employers and profe...
19       T     activities of households as employers of do...
20       U     activities of extraterritorial organization...

In [78]:
sect_df = pd.merge(sect_df,sect_names,on = 'section')
sect_df.rename(columns = {'deets':'name'},inplace=True)

In [79]:
sect_df

section                                            details  \
0        A     Growing of non-perennial crops Growing of c...   
1        B     mining of hard coal mining of hard coal Thi...   
2        C     Processing and preserving of meat processin...   
3        D     electric power generation, transmission and...   
4        E     Water collection, treatment and supply Wate...   
5        F     Construction of buildings Construction of b...   
6        G     Sale of motor vehicles Sale of motor vehicl...   
7        H     transport via railways passenger rail trans...   
8        I     Short term accommodation activities Short t...   
9        J     publishing of books, periodicals and other ...   
10       K     monetary intermediation Central banking Thi...   
11       L     real estate activities with own or leased p...   
12       M     legal activities legal activities This clas...   
13       N     renting and leasing of motor vehicles renti...   
14       O     administration of the State and the economi...   
15       P     primary education primary education Pre-pri...   
16       Q     hospital activities hospital activities Thi...   
17       R     Creative, arts and entertainment activities...   
18       S     activities of business, employers and profe...   
19       T     activities of households as employers of do...   
20       U     activities of extraterritorial organization...   

                                                 name  
0                   Agriculture, forestry and fishing  
1                                Mining and quarrying  
2                                       Manufacturing  
3   Electricity, gas, steam and air conditioning s...  
4   Water supply; sewerage, waste management and r...  
5                                        Construction  
6   Wholesale and retail trade; repair of motor ve...  
7                          Transportation and storage  
8           Accommodation and Food service activities  
9                       Information and communication  
10                 Financial and insurance activities  
11                             Real estate activities  
12  Professional, scientific and technical activities  
13      Administrative and support service activities  
14  Public administration and defence; compulsory ...  
15                                          Education  
16            Human health and social work activities  
17                 Arts, entertainment and recreation  
18                           Other service activities  
19  Activities of households as employers; undiffe...  
20  Activities of extraterritorial organizations a...

### wrting them onto csvs

In [81]:
nic_df_class.to_csv('nic_class.csv')
nic_df_subclass.to_csv('nic_subclass.csv')
nic_df_group.to_csv('nic_group.csv')
nic_df_division.to_csv('nic_division.csv')
sect_df.to_csv('nic_section.csv')
div_sec_dict.to_csv('div_to_sec_dict.csv')

In [82]:
nic_df_class

class                                            details
0    0111   Growing of cereals (except rice), leguminous ...
1    0112   Growing of rice This class includes the growi...
2    0113   Growing of vegetables and melons, roots and t...
3    0114   Growing of sugar cane This class excludes: - ...
4    0115   Growing of tobacco This class includes growin...
5    0116   Growing of fibre crops Growing of cotton Grow...
6    0119   Growing of other non-perennial crop This clas...
7    0121   Growing of grapes This class includes growing...
8    0122   Growing of tropical and subtropical fruits Gr...
9    0123   Growing of citrus fruits Growing of oranges G...
10   0124   Growing of pome fruits and stone fruits Growi...
11   0125   Growing of other tree and bush fruits and nut...
12   0126   Growing of oleaginous fruits This class exclu...
13   0127   Growing of beverage crops Growing of tea Grow...
14   0128   Growing of spices, aromatic, drug and pharmac...
15   0129   Growing of other perennial crops This class e...
16   0130   plant propagation This class includes the pro...
17   0141   raising of cattle and buffaloes This class ex...
18   0142   raising of horses and other equines This clas...
19   0143   raising and breeding of camels and camelids T...
20   0144   raising of sheep and goats This class exclude...
21   0145   raising of swine/pigs Raising of swine/pigs (...
22   0146   raising of poultry This class excludes: - pro...
23   0149   raising of other animals This class excludes:...
24   0150   mixed farming This class includes the combine...
25   0161   Support activities for crop production This c...
26   0162   Support activities for animal production This...
27   0163   post-harvest crop activities This class exclu...
28   0164   Seed processing for propagation This class in...
29   0170   hunting, trapping and related service activit...
..    ...                                                ...
385  9000   Dramatic arts, music and other arts activitie...
386  9101   library and archives activities This class in...
387  9102   museums activities and operation of historica...
388  9103   botanical and zoological gardens and nature r...
389  9200   Gambling and betting activities This class in...
390  9311   operation of sports facilities This class inc...
391  9312   activities of sports clubs This class include...
392  9319   other sports activities This class includes a...
393  9321   activities of amusement parks and theme parks...
394  9329   other amusement and recreation activities n.e...
395  9411   activities of business and employers membersh...
396  9412   activities of professional membership organiz...
397  9420   activities of trade unions This class include...
398  9491   activities of religious organizations This cl...
399  9499   activities of other membership organizations ...
400  9511   repair of computers and peripheral equipment ...
401  9512   repair of communication equipment This class ...
402  9521   repair of consumer electronics This class inc...
403  9522   repair of household appliances and home and g...
404  9523   repair of footwear and leather goods Repair o...
405  9524   repair of furniture and home furnishings Repa...
406  9529   repair of personal and household goods, n.e.c...
407  9601   Washing and (dry-) cleaning of textile and fu...
408  9602   hairdressing and other beauty treatment This ...
409  9603   Funeral and related activities This class inc...
410  9609   other personal service activities n.e.c. Soci...
411  9700   activities of households as employers of dome...
412  9810   undifferentiated goods-producing activities o...
413  9820   undifferentiated service-producing activities...
414  9900   activities of extraterritorial organizations ...

[415 rows x 2 columns]

In [83]:
nic_df_subclass


subclass                                            details
0       01111                                   Growing of wheat
1       01112                Growing of jowar, bajra and millets
2       01113                           Growing of other cereals
3       01114   Growing of pulses (dal) and other leguminous ...
4       01115                        Growing of mustard oil seed
5       01116                      Growing of groundnut oil seed
6       01117                      Growing of sunflower oil seed
7       01118                      Growing of soya bean oil seed
8       01119                         Growing of other oil seeds
9       01121                    Organic farming of basmati rice
10      01122                Organic farming of non-basmati rice
11      01123                  Inorganic farming of basmati rice
12      01124              Inorganic farming of non-basmati rice
13      01131   Growing of asparagus, cabbages, cauliflower, ...
14      01132   Growing of cucumbers, gherkins, aubergines, t...
15      01133                                   Growing of onion
16      01134   Growing of carrots, beets,turnips, garlic, le...
17      01135   Growing of potatoes and other tubers such as ...
18      01136                  Growing of mushrooms and truffles
19      01137      Growing of vegetable seeds (except beet seed)
20      01139                      Growing of vegetables, n.e.c.
21      01140                              Growing of sugar cane
22      01150                                 Growing of tobacco
23      01161                                  Growing of cotton
24      01162                                    Growing of jute
25      01169                       Growing of other fibre crops
26      01191                                    Growing of rose
27      01192                               Growing of gladiolus
28      01193   Growing of other flowers, including productio...
29      01199   Growing of other non-perennial crops includin...
...       ...                                                ...
1307    95111   Repair and maintenance of computer and periph...
1308    95112   Repair and maintenance of automated terminals...
1309    95120                  Repair of communication equipment
1310    95210                     Repair of consumer electronics
1311    95221   Repair and servicing of household appliances ...
1312    95222   Repair and servicing of home and garden equip...
1313    95230               Repair of footwear and leather goods
1314    95240           Repair of furniture and home furnishings
1315    95291                                 Repair of bicycles
1316    95292                  Repair and alteration of clothing
1317    95293                 Repair and alteration of jewellery
1318    95294          Repair of watches, clocks and their parts
1319    95295                      Repair of musical instruments
1320    95299   Repair of other personal and household goods ...
1321    95494            Motor driving school (non-professional)
1322    96010   Washing and (dry-) cleaning of textile and fu...
1323    96020            Hairdressing and other beauty treatment
1324    96030                     Funeral and related activities
1325    96091   Social activities such as escort services, ma...
1326    96092   Pet care services such as boarding, grooming ...
1327    96903      Shoe shiners, porters, valet car parkers etc.
1328    96904   Coin-operated personal service machines such ...
1329    96905   Activities of sauna and steam baths, massage ...
1330    96906       Astrological and spiritualistsâ€™ activities
1331    96907   Activities of aaya, dhai, governess, baby sit...
1332    96908   General household maintenance activities like...
1333    97000   Activities of households as employers of dome...
1334    98100   Undifferentiated goods-producing activities o...
1335    98200   Undifferentiated service-producing activities...
1336    99000   Activities of extraterri

In [84]:
nic_df_group

group                                            details
0     011   Growing of non-perennial crops Growing of cer...
1     012   Growing of perennial crops Growing of grapes ...
2     013   plant propagation plant propagation This clas...
3     014   animal production raising of cattle and buffa...
4     015   mixed farming mixed farming This class includ...
5     016   Support activities to agriculture and post-ha...
6     017   hunting, trapping and related service activit...
7     021   Silviculture and other forestry activities Si...
8     022   logging logging This class excludes: - growin...
9     023   Gathering of non-wood forest products Gatheri...
10    024   Support services to forestry Support services...
11    031   Fishing Marine fishing This class excludes: #...
12    032   aquaculture marine aquaculture This class exc...
13    051   mining of hard coal mining of hard coal This ...
14    052   mining of lignite mining of lignite This clas...
15    061   extraction of crude petroleum extraction of c...
16    062   extraction of natural gas extraction of natur...
17    071   mining of iron ores mining of iron ores This ...
18    072   mining of non-ferrous metal ores mining of ur...
19    081   quarrying of stone, sand and clay quarrying o...
20    089   mining and quarrying n.e.c. mining of chemica...
21    091   Support activities for petroleum and natural ...
22    099   Support activities for other mining and quarr...
23    101   Processing and preserving of meat processing ...
24    102   Processing and preserving of fish, crustacean...
25    103   processing and preserving of fruit and vegeta...
26    104   manufacture of vegetable and animal oils and ...
27    105   manufacture of dairy products manufacture of ...
28    106   manufacture of grain mill products, starches ...
29    107   manufacture of other food products manufactur...
..    ...                                                ...
208   843   Compulsory social security activities Compuls...
209   851   primary education primary education Pre-prima...
210   852   Secondary education General secondary educati...
211   853   higher education higher education Higher educ...
212   854   other education Sports and recreation educati...
213   855   educational support services educational supp...
214   861   hospital activities hospital activities This ...
215   862   medical and dental practice activities medica...
216   869   other human health activities other human hea...
217   871   nursing care facilities nursing care faciliti...
218   872   residential care activities for mental retard...
219   873   residential care activities for the elderly a...
220   879   other residential care activities n.e.c. othe...
221   881   Social work activities without accommodation ...
222   889   other social work activities without accommod...
223   900   Creative, arts and entertainment activities D...
224   910   libraries, archives, museums and other cultur...
225   920   Gambling and betting activities Gambling and ...
226   931   Sports activities operation of sports facilit...
227   932   other amusement and recreation activities act...
228   941   activities of business, employers and profess...
229   942   activities of trade unions activities of trad...
230   949   activities of other membership organizations ...
231   951   repair of computers and communication equipme...
232   952   repair of personal and household goods repair...
233   960   other personal service activities Washing and...
234   970   activities of households as employers of dome...
235   981   undifferentiated goods-producing activities o...
236   982   undifferentiated service-producing activities...
237   990   activities of extraterritorial organizations ...

[238 rows x 2 columns]

In [85]:
nic_df_division

division                                            details  \
0        01    Growing of non-perennial crops Growing of ce...   
1        02    Silviculture and other forestry activities S...   
2        03    Fishing Marine fishing This class excludes: ...   
3        05    mining of hard coal mining of hard coal This...   
4        06    extraction of crude petroleum extraction of ...   
5        07    mining of iron ores mining of iron ores This...   
6        08    quarrying of stone, sand and clay quarrying ...   
7        09    Support activities for petroleum and natural...   
8        10    Processing and preserving of meat processing...   
9        11    manufacture of beverages Distilling, rectify...   
10       12    manufacture of tobacco products manufacture ...   
11       13    Spinning, weaving and finishing of textiles ...   
12       14    manufacture of wearing apparel, except fur a...   
13       15    tanning and dressing of leather; manufacture...   
14       16    Saw milling and planing of wood Saw milling ...   
15       17    manufacture of paper and paper products manu...   
16       18    printing and service activities related to p...   
17       19    manufacture of coke oven products manufactur...   
18       20    manufacture of basic chemicals, fertilizer a...   
19       21    manufacture of pharmaceuticals, medicinal ch...   
20       22    manufacture of rubber products manufacture o...   
21       23    manufacture of glass and glass products manu...   
22       24    manufacture of basic iron and steel manufact...   
23       25    manufacture of structural metal products, ta...   
24       26    manufacture of electronic components manufac...   
25       27    manufacture of electric motors, generators, ...   
26       28    manufacture of general purpose machinery man...   
27       29    manufacture of motor vehicles manufacture of...   
28       30    building of ships and boats Building of ship...   
29       31    manufacture of furniture manufacture of furn...   
..      ...                                                ...   
58       66    Activities auxiliary to financial service ac...   
59       68    real estate activities with own or leased pr...   
60       69    legal activities legal activities This class...   
61       70    Activities of head offices Activities of hea...   
62       71    architectural and engineering activities and...   
63       72    research and experimental developmenton natu...   
64       73    advertising advertising This class includes ...   
65       74    Specialized design activities Specialized de...   
66       75    veterinary activities veterinary activities ...   
67       77    renting and leasing of motor vehicles rentin...   
68       78    activities of employment placement agencies ...   
69       79    travel agency and tour operator activities t...   
70       80    private security activities private security...   
71       81    Combined facilities support activities Combi...   
72       82    Office administrative and support activities...   
73       84    administration of the State and the economic...   
74       85    primary education primary education Pre-prim...   
75       86    hospital activities hospital activities This...   
76       87    nursing care facilities nursing care facilit...   
77       88    Social work activities without accommodation...   
78       90    Creative, arts and entertainment activities ...   
79       91    libraries, archives, museums and other cultu...   
80       92    Gambling and betting activities Gambling and...   
81       93    Sports activities operation of sports facili...   
82       94    activities of business, employers and profes...   
83       95    repair of computers and communication equipm...   
84       96    other personal service activities Washing an...   
85       97    activities of households as employers of dom...   
86       98    undifferentiated goods-produ

In [86]:
sect_df

section                                            details  \
0        A     Growing of non-perennial crops Growing of c...   
1        B     mining of hard coal mining of hard coal Thi...   
2        C     Processing and preserving of meat processin...   
3        D     electric power generation, transmission and...   
4        E     Water collection, treatment and supply Wate...   
5        F     Construction of buildings Construction of b...   
6        G     Sale of motor vehicles Sale of motor vehicl...   
7        H     transport via railways passenger rail trans...   
8        I     Short term accommodation activities Short t...   
9        J     publishing of books, periodicals and other ...   
10       K     monetary intermediation Central banking Thi...   
11       L     real estate activities with own or leased p...   
12       M     legal activities legal activities This clas...   
13       N     renting and leasing of motor vehicles renti...   
14       O     administration of the State and the economi...   
15       P     primary education primary education Pre-pri...   
16       Q     hospital activities hospital activities Thi...   
17       R     Creative, arts and entertainment activities...   
18       S     activities of business, employers and profe...   
19       T     activities of households as employers of do...   
20       U     activities of extraterritorial organization...   

                                                 name  
0                   Agriculture, forestry and fishing  
1                                Mining and quarrying  
2                                       Manufacturing  
3   Electricity, gas, steam and air conditioning s...  
4   Water supply; sewerage, waste management and r...  
5                                        Construction  
6   Wholesale and retail trade; repair of motor ve...  
7                          Transportation and storage  
8           Accommodation and Food service activities  
9                       Information and communication  
10                 Financial and insurance activities  
11                             Real estate activities  
12  Professional, scientific and technical activities  
13      Administrative and support service activities  
14  Public administration and defence; compulsory ...  
15                                          Education  
16            Human health and social work activities  
17                 Arts, entertainment and recreation  
18                           Other service activities  
19  Activities of households as employers; undiffe...  
20  Activities of extraterritorial organizations a...